<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Seyed Saber Naseralavi">
<meta name="author" content="Seyedali Mirjalili">
<meta name="dcterms.date" content="2026-07-04">

<title>The Chess Algorithm: A Novel Metaheuristic Optimization Technique with Applications in Transportation Network Engineering</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="paper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap-9c85a275a43e669dc390249f28684fdb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation"><span class="header-section-number">1.1</span> Motivation</a></li>
  <li><a href="#a-brief-map-of-the-metaheuristic-landscape" id="toc-a-brief-map-of-the-metaheuristic-landscape" class="nav-link" data-scroll-target="#a-brief-map-of-the-metaheuristic-landscape"><span class="header-section-number">1.2</span> A brief map of the metaheuristic landscape</a></li>
  <li><a href="#why-chess" id="toc-why-chess" class="nav-link" data-scroll-target="#why-chess"><span class="header-section-number">1.3</span> Why chess?</a></li>
  <li><a href="#contributions-and-scope" id="toc-contributions-and-scope" class="nav-link" data-scroll-target="#contributions-and-scope"><span class="header-section-number">1.4</span> Contributions and scope</a></li>
  </ul></li>
  <li><a href="#sec-ca" id="toc-sec-ca" class="nav-link" data-scroll-target="#sec-ca"><span class="header-section-number">2</span> The Chess Algorithm</a>
  <ul class="collapse">
  <li><a href="#conceptual-mapping" id="toc-conceptual-mapping" class="nav-link" data-scroll-target="#conceptual-mapping"><span class="header-section-number">2.1</span> Conceptual mapping</a></li>
  <li><a href="#initialization" id="toc-initialization" class="nav-link" data-scroll-target="#initialization"><span class="header-section-number">2.2</span> Initialization</a></li>
  <li><a href="#role-assignment" id="toc-role-assignment" class="nav-link" data-scroll-target="#role-assignment"><span class="header-section-number">2.3</span> Role assignment</a></li>
  <li><a href="#development-schedule" id="toc-development-schedule" class="nav-link" data-scroll-target="#development-schedule"><span class="header-section-number">2.4</span> Development schedule</a></li>
  <li><a href="#piece-movement-operators" id="toc-piece-movement-operators" class="nav-link" data-scroll-target="#piece-movement-operators"><span class="header-section-number">2.5</span> Piece movement operators</a></li>
  <li><a href="#strategic-mechanisms" id="toc-strategic-mechanisms" class="nav-link" data-scroll-target="#strategic-mechanisms"><span class="header-section-number">2.6</span> Strategic mechanisms</a>
  <ul class="collapse">
  <li><a href="#pinning" id="toc-pinning" class="nav-link" data-scroll-target="#pinning"><span class="header-section-number">2.6.1</span> Pinning</a></li>
  <li><a href="#sacrifice" id="toc-sacrifice" class="nav-link" data-scroll-target="#sacrifice"><span class="header-section-number">2.6.2</span> Sacrifice</a></li>
  <li><a href="#sec-enpassant" id="toc-sec-enpassant" class="nav-link" data-scroll-target="#sec-enpassant"><span class="header-section-number">2.6.3</span> En passant (adaptive local capture)</a></li>
  <li><a href="#castling" id="toc-castling" class="nav-link" data-scroll-target="#castling"><span class="header-section-number">2.6.4</span> Castling</a></li>
  <li><a href="#threefold-repetition-diversity-preservation" id="toc-threefold-repetition-diversity-preservation" class="nav-link" data-scroll-target="#threefold-repetition-diversity-preservation"><span class="header-section-number">2.6.5</span> Threefold repetition (diversity preservation)</a></li>
  <li><a href="#checkmate" id="toc-checkmate" class="nav-link" data-scroll-target="#checkmate"><span class="header-section-number">2.6.6</span> Checkmate</a></li>
  </ul></li>
  <li><a href="#parameter-summary" id="toc-parameter-summary" class="nav-link" data-scroll-target="#parameter-summary"><span class="header-section-number">2.7</span> Parameter summary</a></li>
  <li><a href="#pseudocode" id="toc-pseudocode" class="nav-link" data-scroll-target="#pseudocode"><span class="header-section-number">2.8</span> Pseudocode</a></li>
  <li><a href="#flowchart" id="toc-flowchart" class="nav-link" data-scroll-target="#flowchart"><span class="header-section-number">2.9</span> Flowchart</a></li>
  <li><a href="#properties-and-design-rationale" id="toc-properties-and-design-rationale" class="nav-link" data-scroll-target="#properties-and-design-rationale"><span class="header-section-number">2.10</span> Properties and design rationale</a></li>
  </ul></li>
  <li><a href="#sec-benchmarks" id="toc-sec-benchmarks" class="nav-link" data-scroll-target="#sec-benchmarks"><span class="header-section-number">3</span> Benchmark Experiments</a>
  <ul class="collapse">
  <li><a href="#experimental-protocol" id="toc-experimental-protocol" class="nav-link" data-scroll-target="#experimental-protocol"><span class="header-section-number">3.1</span> Experimental protocol</a></li>
  <li><a href="#descriptive-results" id="toc-descriptive-results" class="nav-link" data-scroll-target="#descriptive-results"><span class="header-section-number">3.2</span> Descriptive results</a></li>
  <li><a href="#convergence-behavior" id="toc-convergence-behavior" class="nav-link" data-scroll-target="#convergence-behavior"><span class="header-section-number">3.3</span> Convergence behavior</a></li>
  <li><a href="#statistical-tests" id="toc-statistical-tests" class="nav-link" data-scroll-target="#statistical-tests"><span class="header-section-number">3.4</span> Statistical tests</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">3.5</span> Discussion</a></li>
  </ul></li>
  <li><a href="#sec-transport" id="toc-sec-transport" class="nav-link" data-scroll-target="#sec-transport"><span class="header-section-number">4</span> Transportation Application: Arterial Signal Coordination</a>
  <ul class="collapse">
  <li><a href="#problem-statement" id="toc-problem-statement" class="nav-link" data-scroll-target="#problem-statement"><span class="header-section-number">4.1</span> Problem statement</a></li>
  <li><a href="#optimization-model" id="toc-optimization-model" class="nav-link" data-scroll-target="#optimization-model"><span class="header-section-number">4.2</span> Optimization model</a></li>
  <li><a href="#experimental-setup" id="toc-experimental-setup" class="nav-link" data-scroll-target="#experimental-setup"><span class="header-section-number">4.3</span> Experimental setup</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4.4</span> Results</a></li>
  <li><a href="#the-best-coordination-plan-found" id="toc-the-best-coordination-plan-found" class="nav-link" data-scroll-target="#the-best-coordination-plan-found"><span class="header-section-number">4.5</span> The best coordination plan found</a></li>
  <li><a href="#practical-remarks" id="toc-practical-remarks" class="nav-link" data-scroll-target="#practical-remarks"><span class="header-section-number">4.6</span> Practical remarks</a></li>
  </ul></li>
  <li><a href="#sec-mealpy" id="toc-sec-mealpy" class="nav-link" data-scroll-target="#sec-mealpy"><span class="header-section-number">5</span> Extended Comparison on Independent Implementations</a>
  <ul class="collapse">
  <li><a href="#motivation-1" id="toc-motivation-1" class="nav-link" data-scroll-target="#motivation-1"><span class="header-section-number">5.1</span> Motivation</a></li>
  <li><a href="#problem-p1-the-arterial-signal-timing-instance" id="toc-problem-p1-the-arterial-signal-timing-instance" class="nav-link" data-scroll-target="#problem-p1-the-arterial-signal-timing-instance"><span class="header-section-number">5.2</span> Problem P1: the arterial signal timing instance</a></li>
  <li><a href="#problem-p2-continuous-berth-allocation-with-a-known-optimum" id="toc-problem-p2-continuous-berth-allocation-with-a-known-optimum" class="nav-link" data-scroll-target="#problem-p2-continuous-berth-allocation-with-a-known-optimum"><span class="header-section-number">5.3</span> Problem P2: continuous berth allocation with a known optimum</a></li>
  <li><a href="#what-this-section-does-and-does-not-claim" id="toc-what-this-section-does-and-does-not-claim" class="nav-link" data-scroll-target="#what-this-section-does-and-does-not-claim"><span class="header-section-number">5.4</span> What this section does and does not claim</a></li>
  </ul></li>
  <li><a href="#conclusions-and-future-work" id="toc-conclusions-and-future-work" class="nav-link" data-scroll-target="#conclusions-and-future-work"><span class="header-section-number">6</span> Conclusions and Future Work</a></li>
  <li><a href="#conclusions-and-future-work-1" id="toc-conclusions-and-future-work-1" class="nav-link" data-scroll-target="#conclusions-and-future-work-1"><span class="header-section-number">7</span> Conclusions and Future Work</a>
  <ul class="collapse">
  <li><a href="#summary-of-findings" id="toc-summary-of-findings" class="nav-link" data-scroll-target="#summary-of-findings"><span class="header-section-number">7.1</span> Summary of findings</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">7.2</span> Limitations</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work"><span class="header-section-number">7.3</span> Future work</a></li>
  <li><a href="#closing-remark" id="toc-closing-remark" class="nav-link" data-scroll-target="#closing-remark"><span class="header-section-number">7.4</span> Closing remark</a></li>
  </ul></li>
  <li><a href="#data-and-code-availability" id="toc-data-and-code-availability" class="nav-link" data-scroll-target="#data-and-code-availability">Data and code availability</a></li>
  <li><a href="#about-the-corresponding-author" id="toc-about-the-corresponding-author" class="nav-link" data-scroll-target="#about-the-corresponding-author">About the corresponding author</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Chess Algorithm: A Novel Metaheuristic Optimization Technique with Applications in Transportation Network Engineering</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Seyed Saber Naseralavi <a href="mailto:saber_naseralavi@uk.ac.ir" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Civil Engineering, Faculty of Engineering, Shahid Bahonar University of Kerman, Kerman, Iran
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Seyedali Mirjalili </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Centre for Artificial Intelligence Research and Optimization, Torrens University Australia, Brisbane, Australia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>We introduce the Chess Algorithm (CA), a population-based metaheuristic that borrows its search logic from the strategy of chess rather than from foraging or hunting behavior in nature. The population is not homogeneous: at every iteration agents are ranked and assigned the roles of King, Queens, Rooks, Bishops, Knights, and Pawns, and each role moves according to an operator abstracted from the geometry of the corresponding piece. Strategic ideas from the game supply the control machinery. Development governs the exploration–exploitation schedule; sacrifice permits worse moves under a Metropolis-type rule restricted to minor pieces; pinning progressively freezes coordinates around the incumbent; castling exchanges coordinate blocks between the King and the best Rook when doing so helps; en passant performs an opportunistic, self-adaptive local search; and a threefold-repetition rule restores diversity whenever the population collapses onto the incumbent. We evaluate CA on six standard 30-dimensional benchmarks against GA, PSO, SA, and GWO under matched evaluation budgets (30 runs, ANOVA and Wilcoxon tests), where it significantly outperforms GA, PSO, and SA on most of the suite while GWO keeps its known edge on the classical functions. Practical value is then assessed on transportation problems. On the coordinated signal timing of an eight-intersection arterial with a Webster/HCM delay model, CA matches the best solution any competitor finds. In an extended comparison against six algorithms from the independent mealpy library (WOA, SCA, ALO, MFO, HHO, and DE) on the signal problem and on a continuous berth allocation instance with a known global optimum, CA’s placement is assessed against third-party implementations rather than our own. The results support a measured claim: CA is a sound, competitive, and fully reproducible addition to the toolbox of transportation network optimization.</p>
  </div>
</div>


</header>


<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Formats and files.</strong> You are reading the HTML version. The typeset manuscript is also available as <a href="paper.pdf"><strong>PDF</strong> (<code>paper.pdf</code>)</a>. Source code, experiment scripts, and all raw results live in the <a href="https://github.com/sabernaseralavi-60/2026_Chess-Algorithm">GitHub repository</a>.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Author note.</strong> Dr.&nbsp;Seyedali Mirjalili is listed as an invited co-author; his participation is pending confirmation. The invitation reflects how much this study owes to his work on swarm and nature-inspired optimization, and his name will be retained only with his explicit consent.</p>
</div>
</div>
</div>
<p><strong>Keywords:</strong> metaheuristics; chess algorithm; global optimization; benchmark functions; traffic signal timing; berth allocation; transportation networks.</p>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="motivation" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">1.1</span> Motivation</h2>
<p>A large share of the decisions a transportation engineer has to make can be written, after enough simplification, as a global optimization problem:</p>
<p><span id="eq-problem"><span class="math display">\[
\min_{\mathbf{x} \in \Omega} f(\mathbf{x}), \qquad
\Omega = \{\mathbf{x} \in \mathbb{R}^{D} : l_j \le x_j \le u_j,\; j = 1,\dots,D\}.
\tag{1}\]</span></span></p>
<p>The trouble is what <span class="math inline">\(f\)</span> looks like in practice. Signal timing, network design, transit scheduling, detector placement — in each of these the objective is non-convex, often non-differentiable, riddled with local optima, and sometimes expensive to evaluate <span class="citation" data-cites="ceylan2004traffic osorio2013simulation">(<a href="#ref-ceylan2004traffic" role="doc-biblioref">Ceylan &amp; Bell, 2004</a>; <a href="#ref-osorio2013simulation" role="doc-biblioref">Osorio &amp; Bierlaire, 2013</a>)</span>. Exact methods rarely scale to instances of realistic size. This is why metaheuristics have kept their popularity for three decades: they trade the guarantee of optimality for robustness, generality, and a computational budget one can actually afford.</p>
</section>
<section id="a-brief-map-of-the-metaheuristic-landscape" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="a-brief-map-of-the-metaheuristic-landscape"><span class="header-section-number">1.2</span> A brief map of the metaheuristic landscape</h2>
<p>The field grew from two roots. Evolutionary computation gave us the Genetic Algorithm <span class="citation" data-cites="holland1975adaptation goldberg1989genetic">(<a href="#ref-goldberg1989genetic" role="doc-biblioref">Goldberg, 1989</a>; <a href="#ref-holland1975adaptation" role="doc-biblioref">Holland, 1975</a>)</span> and Evolution Strategies <span class="citation" data-cites="beyer2002es">(<a href="#ref-beyer2002es" role="doc-biblioref">Beyer &amp; Schwefel, 2002</a>)</span>. Trajectory methods gave us Simulated Annealing <span class="citation" data-cites="kirkpatrick1983sa">(<a href="#ref-kirkpatrick1983sa" role="doc-biblioref">Kirkpatrick et al., 1983</a>)</span>, whose central idea — accept a worse solution now and then, so you can escape a local minimum — turned out to be one of the most durable in the field. Swarm intelligence arrived in the 1990s with Particle Swarm Optimization <span class="citation" data-cites="kennedy1995pso">(<a href="#ref-kennedy1995pso" role="doc-biblioref">Kennedy &amp; Eberhart, 1995</a>)</span>, Ant Colony Optimization <span class="citation" data-cites="dorigo1996aco">(<a href="#ref-dorigo1996aco" role="doc-biblioref">Dorigo et al., 1996</a>)</span>, Differential Evolution <span class="citation" data-cites="storn1997de">(<a href="#ref-storn1997de" role="doc-biblioref">Storn &amp; Price, 1997</a>)</span>, and later the Artificial Bee Colony <span class="citation" data-cites="karaboga2007abc">(<a href="#ref-karaboga2007abc" role="doc-biblioref">Karaboga &amp; Basturk, 2007</a>)</span>. More recently, Mirjalili and colleagues built a productive line of algorithms by abstracting the social and hunting behavior of animals into compact operators: the Grey Wolf Optimizer <span class="citation" data-cites="mirjalili2014gwo">(<a href="#ref-mirjalili2014gwo" role="doc-biblioref">Mirjalili et al., 2014</a>)</span>, the Ant Lion Optimizer <span class="citation" data-cites="mirjalili2015alo">(<a href="#ref-mirjalili2015alo" role="doc-biblioref">Mirjalili, 2015b</a>)</span>, the Dragonfly Algorithm <span class="citation" data-cites="mirjalili2016dragonfly">(<a href="#ref-mirjalili2016dragonfly" role="doc-biblioref">Mirjalili, 2016a</a>)</span>, the Whale Optimization Algorithm <span class="citation" data-cites="mirjalili2016whale">(<a href="#ref-mirjalili2016whale" role="doc-biblioref">Mirjalili &amp; Lewis, 2016</a>)</span>, the Sine Cosine Algorithm <span class="citation" data-cites="mirjalili2016sca">(<a href="#ref-mirjalili2016sca" role="doc-biblioref">Mirjalili, 2016b</a>)</span>, and the Salp Swarm Algorithm <span class="citation" data-cites="mirjalili2017salp">(<a href="#ref-mirjalili2017salp" role="doc-biblioref">Mirjalili et al., 2017</a>)</span>, among others.</p>
<p>Reading this literature, two things stand out. First, almost every swarm algorithm treats its agents identically: one update equation, applied to everyone, with only position and fitness distinguishing one agent from the next. Yet division of labor among <em>unequal</em> agents is one of the oldest tricks in both nature and human strategy. Second, the quality of a metaheuristic usually stands or falls on how it schedules the transition from exploration to exploitation <span class="citation" data-cites="mirjalili2014gwo">(<a href="#ref-mirjalili2014gwo" role="doc-biblioref">Mirjalili et al., 2014</a>)</span>, and mechanisms that adapt this transition to what the search is actually observing — rather than to elapsed time alone — remain surprisingly rare.</p>
<p>We should also be upfront about why proposing yet another metaheuristic is defensible at all. The No-Free-Lunch theorem <span class="citation" data-cites="wolpert1997nfl">(<a href="#ref-wolpert1997nfl" role="doc-biblioref">Wolpert &amp; Macready, 1997</a>)</span> rules out a universally dominant optimizer, so the honest goal is not to win everywhere; it is to contribute a genuinely different inductive bias and to show the problem class where that bias earns its keep.</p>
</section>
<section id="why-chess" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="why-chess"><span class="header-section-number">1.3</span> Why chess?</h2>
<p>Chess offers exactly the two ingredients we just found missing. Its pieces are radically unequal: the queen sweeps the whole board, rooks travel along files and ranks, bishops along diagonals, knights jump over anything in the way, and pawns crawl forward one square at a time while quietly defining the structure of the position. Mapped onto a search population, this suggests sub-groups performing qualitatively different moves around one common reference point — the King, which in our setting is the best solution found so far.</p>
<p>The game also comes with a mature strategic vocabulary, refined over centuries of analysis. Development says: mobilize your forces early, consolidate later. A sacrifice gives up material now for a positional advantage later. Pinning immobilizes a piece against something more valuable behind it. Castling is a safeguarded structural rearrangement; en passant, an opportunistic capture available only under narrow conditions; the threefold-repetition rule declares a draw when the position keeps repeating. Each of these has a natural algorithmic reading — exploration schedules, acceptance of deteriorating moves, variable fixation, elite restructuring, adaptive local search, and diversity preservation, respectively.</p>
<p>The Chess Algorithm (CA) proposed here formalizes that mapping. To avoid a misunderstanding that came up more than once when we described the idea to colleagues: CA does not play chess and searches no game tree. It borrows the strategic grammar of the game, nothing more, and its per-iteration cost is comparable to that of GA or PSO.</p>
</section>
<section id="contributions-and-scope" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="contributions-and-scope"><span class="header-section-number">1.4</span> Contributions and scope</h2>
<p>The paper contributes, in order: a complete mathematical specification of CA — initialization, rank-based role assignment, six movement operators, five strategic mechanisms, and a diversity rule (<a href="#sec-ca" class="quarto-xref">Section&nbsp;2</a>); a controlled benchmark study on six standard test functions in 30 dimensions against GA, PSO, SA, and GWO under matched budgets, with nonparametric testing following <span class="citation" data-cites="derrac2011nonparametric">Derrac et al. (<a href="#ref-derrac2011nonparametric" role="doc-biblioref">2011</a>)</span> (<a href="#sec-benchmarks" class="quarto-xref">Section&nbsp;3</a>); a transportation case study on coordinated signal timing of an eight-intersection arterial with a Webster/HCM delay model <span class="citation" data-cites="webster1958traffic roess2019traffic">(<a href="#ref-roess2019traffic" role="doc-biblioref">Roess et al., 2019</a>; <a href="#ref-webster1958traffic" role="doc-biblioref">Webster, 1958</a>)</span> (<a href="#sec-transport" class="quarto-xref">Section&nbsp;4</a>); an extended comparison against six third-party implementations from the <code>mealpy</code> library on two transportation problems, one of which has a known global optimum (<a href="#sec-mealpy" class="quarto-xref">Section&nbsp;5</a>); and a fully reproducible open-source implementation.</p>
<p>A remark on tone before we start. We report results with deliberate restraint and no claim of universal superiority; GWO, in particular, remains stronger on several classical benchmarks, and we say so plainly where it happens. The claim we do defend is narrower: CA is well-founded, novel, and competitive, and on the transportation problems that motivated it in the first place it performs on par with — and against some widely used algorithms, better than — the available alternatives.</p>
</section>
</section>
<section id="sec-ca" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The Chess Algorithm</h1>
<section id="conceptual-mapping" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="conceptual-mapping"><span class="header-section-number">2.1</span> Conceptual mapping</h2>
<p>CA maintains a population of <span class="math inline">\(N\)</span> candidate solutions <span class="math inline">\(\mathbf{X}_i \in \Omega \subset \mathbb{R}^D\)</span>, treated as pieces playing “toward” the global optimum. <a href="#tbl-mapping" class="quarto-xref">Table&nbsp;1</a> summarizes how the vocabulary of the game maps onto algorithmic mechanisms.</p>
<div id="tbl-mapping" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mapping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Mapping between chess concepts and CA mechanisms.
</figcaption>
<div aria-describedby="tbl-mapping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Chess concept</th>
<th>Algorithmic role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>King</td>
<td>Incumbent best solution (never lost)</td>
</tr>
<tr class="even">
<td>Queen, Rook, Bishop, Knight, Pawn</td>
<td>Heterogeneous movement operators</td>
</tr>
<tr class="odd">
<td>Development (opening principle)</td>
<td>Time-decaying step-scale <span class="math inline">\(a(t)\)</span></td>
</tr>
<tr class="even">
<td>Sacrifice</td>
<td>Probabilistic acceptance of worse moves (minor pieces only)</td>
</tr>
<tr class="odd">
<td>Pinning</td>
<td>Progressive freezing of coordinates to the King’s values</td>
</tr>
<tr class="even">
<td>Castling</td>
<td>Safeguarded coordinate-block exchange King <span class="math inline">\(\leftrightarrow\)</span> Rook</td>
</tr>
<tr class="odd">
<td>En passant</td>
<td>Opportunistic, self-adaptive local capture around the King</td>
</tr>
<tr class="even">
<td>Pawn promotion</td>
<td>Rank-based role reassignment each iteration</td>
</tr>
<tr class="odd">
<td>Threefold repetition</td>
<td>Re-deployment of agents that collapse onto the King</td>
</tr>
<tr class="even">
<td>Checkmate</td>
<td>Termination criterion</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>One point deserves emphasis: CA borrows the strategic grammar of chess as an inductive bias, not the game itself. An iteration costs <span class="math inline">\(\mathcal{O}(ND + N \log N)\)</span> arithmetic operations (the movement updates plus the sort that drives role assignment) and <span class="math inline">\(N + 3\)</span> function evaluations — <span class="math inline">\(N\)</span> piece moves plus three en-passant probes — with one extra castling probe every <span class="math inline">\(c\)</span> iterations. That is the same order as GA, PSO, or GWO. The exact evaluation accounting used in the experiments is spelled out in <a href="#sec-benchmarks" class="quarto-xref">Section&nbsp;3</a>.</p>
</section>
<section id="initialization" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="initialization"><span class="header-section-number">2.2</span> Initialization</h2>
<p>The board is set up by scattering the <span class="math inline">\(N\)</span> pieces uniformly over the feasible box:</p>
<p><span id="eq-init"><span class="math display">\[
\mathbf{X}_i^{(0)} = \mathbf{l} + (\mathbf{u} - \mathbf{l}) \circ \mathbf{r}_i, \qquad
\mathbf{r}_i \sim \mathcal{U}(0,1)^D, \quad i = 1, \dots, N,
\tag{2}\]</span></span></p>
<p>where <span class="math inline">\(\mathbf{l}\)</span> and <span class="math inline">\(\mathbf{u}\)</span> are the bound vectors and <span class="math inline">\(\circ\)</span> is the elementwise (Hadamard) product. All positions are evaluated once and the population is sorted by fitness before the first move is played.</p>
</section>
<section id="role-assignment" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="role-assignment"><span class="header-section-number">2.3</span> Role assignment</h2>
<p>Let <span class="math inline">\(\pi\)</span> be the permutation of <span class="math inline">\(\{1, \dots, N\}\)</span> that sorts the population,</p>
<p><span id="eq-roles"><span class="math display">\[
f\big(\mathbf{X}_{\pi(1)}\big) \le f\big(\mathbf{X}_{\pi(2)}\big) \le \dots \le f\big(\mathbf{X}_{\pi(N)}\big).
\tag{3}\]</span></span></p>
<p>The best agent <span class="math inline">\(\mathbf{K} = \mathbf{X}_{\pi(1)}\)</span> is the King. The following ranks are partitioned, in order, into Queens <span class="math inline">\(\mathcal{Q}\)</span>, Rooks <span class="math inline">\(\mathcal{R}\)</span>, Bishops <span class="math inline">\(\mathcal{B}\)</span>, and Knights <span class="math inline">\(\mathcal{N}\)</span>, with</p>
<p><span class="math display">\[
|\mathcal{Q}| = \max(1, \lfloor \rho_q N \rceil), \quad
|\mathcal{R}| = \max(1, \lfloor \rho_r N \rceil), \quad
|\mathcal{B}| = \max(1, \lfloor \rho_b N \rceil), \quad
|\mathcal{N}| = \max(1, \lfloor \rho_n N \rceil),
\]</span></p>
<p>where <span class="math inline">\(\lfloor \cdot \rceil\)</span> denotes rounding and <span class="math inline">\((\rho_q, \rho_r, \rho_b, \rho_n) = (0.10, 0.15, 0.15, 0.20)\)</span>. Whatever remains becomes the Pawns <span class="math inline">\(\mathcal{P}\)</span>. Because the assignment is redone after every iteration, a pawn that stumbles into a good region is simply a strong piece the next time roles are dealt. Promotion, in other words, falls out of re-ranking for free; no extra machinery is needed.</p>
</section>
<section id="development-schedule" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="development-schedule"><span class="header-section-number">2.4</span> Development schedule</h2>
<p>Opening theory tells a player to develop pieces quickly; endgames reward patience and precision. CA encodes this with a linearly decaying step-scale coefficient,</p>
<p><span id="eq-development"><span class="math display">\[
a(t) = 2\left(1 - \frac{t}{T}\right),
\tag{4}\]</span></span></p>
<p>with <span class="math inline">\(t\)</span> the current iteration and <span class="math inline">\(T\)</span> the total budget — the convention popularized by <span class="citation" data-cites="mirjalili2014gwo">Mirjalili et al. (<a href="#ref-mirjalili2014gwo" role="doc-biblioref">2014</a>)</span>. Every piece move scales with <span class="math inline">\(a(t)\)</span>, so the swarm plays big developing moves early and fine maneuvers late.</p>
</section>
<section id="piece-movement-operators" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="piece-movement-operators"><span class="header-section-number">2.5</span> Piece movement operators</h2>
<p>Write <span class="math inline">\(\mathbf{L} = \mathbf{u} - \mathbf{l}\)</span> for the box width and let <span class="math inline">\(\mathbf{r}, \mathbf{r}' \sim \mathcal{U}(0,1)^D\)</span> be independent random vectors. The five mobile roles then move as follows.</p>
<p><strong>Queen (omnidirectional sweep).</strong> The queen circles the King at a radius tied to her current distance from him:</p>
<p><span id="eq-queen"><span class="math display">\[
\mathbf{X}_i' = \mathbf{K} + a(t)\,(2\mathbf{r} - \mathbf{1}) \circ \max\!\big(|\mathbf{K} - \mathbf{X}_i|,\ \boldsymbol{\sigma}\big),
\tag{5}\]</span></span></p>
<p>where <span class="math inline">\(\boldsymbol{\sigma}\)</span> is the King’s adaptive capture radius from <a href="#sec-enpassant" class="quarto-xref">Section&nbsp;2.6.3</a>. The <span class="math inline">\(\max\)</span> keeps the sweep from collapsing entirely, so queens never stall.</p>
<p><strong>Rook (single-axis move).</strong> One random axis <span class="math inline">\(j\)</span> is chosen and only that coordinate moves:</p>
<p><span id="eq-rook"><span class="math display">\[
X_{i,j}' = K_j + a(t)\,(2r - 1)\,\max\!\big(|K_j - X_{i,j}|,\ 0.01\,L_j\,a(t)\big).
\tag{6}\]</span></span></p>
<p><strong>Bishop (diagonal move).</strong> Two distinct axes <span class="math inline">\(j\)</span> and <span class="math inline">\(k\)</span> receive steps of equal magnitude and random relative sign, which is as close to a diagonal as a box-constrained space allows:</p>
<p><span id="eq-bishop"><span class="math display">\[
\Delta = a(t)\,(2r-1)\,\max\!\Big(\tfrac{1}{2}\big(|K_j - X_{i,j}| + |K_k - X_{i,k}|\big),\ 0.01\,L\,a(t)\Big), \quad
X_{i,j}' = K_j + \Delta,\ \ X_{i,k}' = K_k \pm \Delta.
\tag{7}\]</span></span></p>
<p><strong>Knight (L-shaped jump).</strong> The knight is the one piece that jumps over whatever stands in its way. Relative to a randomly chosen better-ranked peer <span class="math inline">\(\mathbf{P}\)</span>, it drifts toward the peer and then adds an asymmetric <span class="math inline">\(2{:}1\)</span> jump on two random axes:</p>
<p><span id="eq-knight"><span class="math display">\[
\mathbf{X}_i' = \mathbf{X}_i + \mathbf{r} \circ (\mathbf{P} - \mathbf{X}_i), \qquad
X_{i,j}' \mathrel{+}= 2\,a(t)\,\beta\,(2r-1), \quad
X_{i,k}' \mathrel{+}= 1\,a(t)\,\beta\,(2r'-1),
\tag{8}\]</span></span></p>
<p>with <span class="math inline">\(\beta = \overline{|\mathbf{P} - \mathbf{X}_i|}\)</span> the mean coordinate gap. With small probability <span class="math inline">\(0.1\,a(t)/2\)</span> the knight abandons this move and leaps: two coordinates are resampled uniformly in <span class="math inline">\(\Omega\)</span>. This leap is the algorithm’s main long-range restart device. The implementation also ships a heavy-tailed variant in which those two coordinates instead receive a Lévy-flight step <span class="math inline">\(0.05\,L\,s\)</span> generated by Mantegna’s algorithm <span class="citation" data-cites="mantegna1994levy">(<a href="#ref-mantegna1994levy" role="doc-biblioref">Mantegna, 1994</a>)</span>, the mechanism Cuckoo Search made popular <span class="citation" data-cites="yang2009cuckoo">(<a href="#ref-yang2009cuckoo" role="doc-biblioref">Yang &amp; Deb, 2009</a>)</span>:</p>
<p><span id="eq-levy"><span class="math display">\[
s = \frac{u}{|v|^{1/\beta_\ell}}, \qquad
u \sim \mathcal{N}(0, \sigma_u^2), \quad v \sim \mathcal{N}(0, 1), \qquad
\sigma_u = \left[
\frac{\Gamma(1+\beta_\ell)\,\sin(\pi \beta_\ell / 2)}
     {\Gamma\!\big(\tfrac{1+\beta_\ell}{2}\big)\,\beta_\ell\, 2^{(\beta_\ell - 1)/2}}
\right]^{1/\beta_\ell},
\tag{9}\]</span></span></p>
<p>with tail index <span class="math inline">\(\beta_\ell = 1.5\)</span>. Every result in this paper uses the plain uniform leap; the Lévy option is documented for future study rather than used here.</p>
<p><strong>Pawn (steady advance).</strong> Pawns take small steps toward the King and toward a random better-ranked piece <span class="math inline">\(\mathbf{B}\)</span>:</p>
<p><span id="eq-pawn"><span class="math display">\[
\mathbf{X}_i' = \mathbf{X}_i + 0.3\,\mathbf{r} \circ (\mathbf{K} - \mathbf{X}_i) + 0.3\,\mathbf{r}' \circ (\mathbf{B} - \mathbf{X}_i).
\tag{10}\]</span></span></p>
</section>
<section id="strategic-mechanisms" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="strategic-mechanisms"><span class="header-section-number">2.6</span> Strategic mechanisms</h2>
<section id="pinning" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="pinning"><span class="header-section-number">2.6.1</span> Pinning</h3>
<p>With probability <span class="math inline">\(p_{\text{pin}}(t) = 0.5\,t/T\)</span>, a random subset of at most <span class="math inline">\(30\%\)</span> of an agent’s coordinates is pinned to the King’s values and excluded from perturbation. Early on, pinning is rare and the pieces develop freely. Late in the run it concentrates the search on a shrinking set of free dimensions around the incumbent, which is exactly the kind of scheduled exploitation an endgame calls for.</p>
</section>
<section id="sacrifice" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="sacrifice"><span class="header-section-number">2.6.2</span> Sacrifice</h3>
<p>A worsening move <span class="math inline">\(\Delta_i = f(\mathbf{X}_i') - f(\mathbf{X}_i) &gt; 0\)</span> made by a minor piece — a Knight or a Pawn — is still accepted with probability</p>
<p><span id="eq-sacrifice"><span class="math display">\[
p_{\text{acc}} = \exp\!\left(-\frac{\Delta_i}{\theta(t)}\right), \qquad
\theta(t) = \theta_0 \big(f_{\max} - f_{\min}\big)\, e^{-8 t / T},
\tag{11}\]</span></span></p>
<p>with <span class="math inline">\(\theta_0 = 0.1\)</span>. Readers will recognize the Metropolis rule of Simulated Annealing <span class="citation" data-cites="kirkpatrick1983sa">(<a href="#ref-kirkpatrick1983sa" role="doc-biblioref">Kirkpatrick et al., 1983</a>)</span>, but two chess-flavored restrictions change its character. The temperature is scaled by the current fitness spread of the population, which makes the sacrifice budget self-calibrating across problems of wildly different magnitudes. And only minor pieces may be sacrificed: the King and the major pieces are never lost, so the elite of the population cannot be eroded by the acceptance rule.</p>
</section>
<section id="sec-enpassant" class="level3" data-number="2.6.3">
<h3 data-number="2.6.3" class="anchored" data-anchor-id="sec-enpassant"><span class="header-section-number">2.6.3</span> En passant (adaptive local capture)</h3>
<p>Once per iteration the King attempts an en-passant capture. Three trial points are drawn in a sparse Gaussian neighborhood,</p>
<p><span id="eq-enpassant"><span class="math display">\[
\mathbf{Y}_m = \mathbf{K} + \boldsymbol{\sigma} \circ \mathbf{z}_m \circ \mathbf{m}_m, \qquad
\mathbf{z}_m \sim \mathcal{N}(\mathbf{0}, \mathbf{I}),\quad m = 1,2,3,
\tag{12}\]</span></span></p>
<p>where the random binary mask <span class="math inline">\(\mathbf{m}_m\)</span> activates each coordinate with probability <span class="math inline">\(\max(0.2,\ 2/D)\)</span>. Any improving trial replaces the King. The radius <span class="math inline">\(\boldsymbol{\sigma}\)</span> follows a success rule of the kind long used in Evolution Strategies <span class="citation" data-cites="beyer2002es">(<a href="#ref-beyer2002es" role="doc-biblioref">Beyer &amp; Schwefel, 2002</a>)</span>: multiply by <span class="math inline">\(1.3\)</span> after a successful capture, by <span class="math inline">\(0.92\)</span> after a failure, and after <span class="math inline">\(50\)</span> consecutive failures reset to <span class="math inline">\(\boldsymbol{\sigma} = 0.05\,\mathbf{L}\max(a(t), 0.05)\)</span> — a stalemate-avoidance restart. In our experience this mechanism is what keeps CA improving deep into the run, long after a fixed-radius local search would have gone quiet.</p>
</section>
<section id="castling" class="level3" data-number="2.6.4">
<h3 data-number="2.6.4" class="anchored" data-anchor-id="castling"><span class="header-section-number">2.6.4</span> Castling</h3>
<p>Every <span class="math inline">\(c = 10\)</span> iterations the King castles with the best Rook: a contiguous block of up to <span class="math inline">\(D/4\)</span> coordinates is copied from the Rook into a candidate King, and the exchange is kept only if it improves the King. It is a safeguarded structural jump, useful when good partial solutions have been discovered on different “files” of the board and need splicing together.</p>
</section>
<section id="threefold-repetition-diversity-preservation" class="level3" data-number="2.6.5">
<h3 data-number="2.6.5" class="anchored" data-anchor-id="threefold-repetition-diversity-preservation"><span class="header-section-number">2.6.5</span> Threefold repetition (diversity preservation)</h3>
<p>If an agent coincides with the King to numerical precision — something pinning can eventually cause — it is re-deployed uniformly in <span class="math inline">\(\Omega\)</span>, much as the threefold-repetition rule stops a game from going in circles. We did not add this rule for elegance; early prototypes taught us it is essential. Without it, pinning breeds exact clones of the King, every gap-proportional step length collapses to zero, and the search dies quietly in place.</p>
</section>
<section id="checkmate" class="level3" data-number="2.6.6">
<h3 data-number="2.6.6" class="anchored" data-anchor-id="checkmate"><span class="header-section-number">2.6.6</span> Checkmate</h3>
<p>The algorithm stops after <span class="math inline">\(T\)</span> iterations. A stagnation-based early stop would be easy to add, but we keep it disabled in all experiments so that every algorithm consumes the same core budget of <span class="math inline">\(N \times T\)</span> population evaluations.</p>
</section>
</section>
<section id="parameter-summary" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="parameter-summary"><span class="header-section-number">2.7</span> Parameter summary</h2>
<p><a href="#tbl-params" class="quarto-xref">Table&nbsp;2</a> collects the parameters and the single configuration used everywhere in this paper. No per-problem tuning was done, for CA or for any competitor.</p>
<div id="tbl-params" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: CA parameters and the fixed configuration used in all experiments.
</figcaption>
<div aria-describedby="tbl-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 41%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: center;">Symbol</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Role fractions (Queen / Rook / Bishop / Knight)</td>
<td style="text-align: center;"><span class="math inline">\(\rho_q,\rho_r,\rho_b,\rho_n\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.10 / 0.15 / 0.15 / 0.20\)</span></td>
</tr>
<tr class="even">
<td>Development schedule</td>
<td style="text-align: center;"><span class="math inline">\(a(t)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2(1 - t/T)\)</span></td>
</tr>
<tr class="odd">
<td>Pinning probability / cap</td>
<td style="text-align: center;"><span class="math inline">\(p_{\text{pin}}(t)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.5\,t/T\)</span>, at most <span class="math inline">\(30\%\)</span> of coordinates</td>
</tr>
<tr class="even">
<td>Sacrifice constant</td>
<td style="text-align: center;"><span class="math inline">\(\theta_0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.1\)</span></td>
</tr>
<tr class="odd">
<td>Castling period</td>
<td style="text-align: center;"><span class="math inline">\(c\)</span></td>
<td style="text-align: right;"><span class="math inline">\(10\)</span> iterations</td>
</tr>
<tr class="even">
<td>En-passant probes per iteration</td>
<td style="text-align: center;">—</td>
<td style="text-align: right;"><span class="math inline">\(3\)</span></td>
</tr>
<tr class="odd">
<td>En-passant adaptation (success / failure / reset)</td>
<td style="text-align: center;">—</td>
<td style="text-align: right;"><span class="math inline">\(\times 1.3\)</span> / <span class="math inline">\(\times 0.92\)</span> / after <span class="math inline">\(50\)</span> failures</td>
</tr>
<tr class="even">
<td>Knight exploratory-leap distribution</td>
<td style="text-align: center;">—</td>
<td style="text-align: right;">uniform (Lévy, <span class="math inline">\(\beta_\ell = 1.5\)</span>, optional)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="pseudocode" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="pseudocode"><span class="header-section-number">2.8</span> Pseudocode</h2>
<pre><code>Algorithm: Chess Algorithm (CA)
Input: objective f, bounds [l, u], dimension D,
       population N, iterations T
1  Initialize X uniformly in [l, u] (Eq. init); evaluate F; sort; King ← X(1)
2  σ ← 0.1 L; fails ← 0
3  for t = 0 … T−1:
4      a ← 2(1 − t/T);  p_pin ← 0.5 t/T;  θ ← 0.1 (F_max − F_min) e^(−8t/T)
5      Assign roles by rank: Queens 10%, Rooks 15%, Bishops 15%,
         Knights 20%, Pawns rest
6      Move each piece by its operator (Eqs. Queen–Pawn)
7      Pin ≤ 30% of coordinates of each agent to King with prob. p_pin
8      Clip to bounds; evaluate F′
9      Accept improvements; accept worse MINOR pieces with prob. e^(−Δ/θ)
10     En passant: 3 masked Gaussian trials of radius σ around King;
         keep any improvement; adapt σ (×1.3 success / ×0.92 fail;
         stalemate reset after 50 fails)
11     Every 10 iters: Castle — block-swap King↔best Rook, keep if better
12     Threefold repetition: re-deploy agents identical to the King
13     Update King; re-sort population (pawn promotion)
14 return King</code></pre>
</section>
<section id="flowchart" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="flowchart"><span class="header-section-number">2.9</span> Flowchart</h2>
<p><a href="#fig-flowchart" class="quarto-xref">Figure&nbsp;1</a> summarizes one full iteration of the algorithm.</p>
<div id="fig-flowchart" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-flowchart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/ca_flowchart.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:88.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-flowchart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Flowchart of the Chess Algorithm.
</figcaption>
</figure>
</div>
</section>
<section id="properties-and-design-rationale" class="level2" data-number="2.10">
<h2 data-number="2.10" class="anchored" data-anchor-id="properties-and-design-rationale"><span class="header-section-number">2.10</span> Properties and design rationale</h2>
<p><strong>Elitism and convergence.</strong> The King’s fitness never increases: it is replaced only by strictly better points, whether through the population update, en passant, or castling. That elitism buys the usual asymptotic guarantee (<a href="#prp-convergence" class="quarto-xref">Proposition&nbsp;1</a>).</p>
<div id="prp-convergence" class="theorem proposition">
<p><span class="theorem-title"><strong>Proposition 1 (Elitist convergence in probability)</strong></span> Let <span class="math inline">\(f\)</span> be continuous on the compact box <span class="math inline">\(\Omega\)</span> with global minimum <span class="math inline">\(f^{*}\)</span>. Under CA’s update rules, the best-so-far value <span class="math inline">\(f(\mathbf{K}^{(t)})\)</span> converges in probability to <span class="math inline">\(f^{*}\)</span> as <span class="math inline">\(T \to \infty\)</span>.</p>
<p><em>Proof sketch.</em> The King sequence is elitist by construction. At every iteration the Knight’s exploratory leap and the threefold-repetition re-deployment both place uniform probability mass over <span class="math inline">\(\Omega\)</span>, so any open subset — in particular any neighborhood of a global minimizer, whose objective values come within <span class="math inline">\(\varepsilon\)</span> of <span class="math inline">\(f^{*}\)</span> by continuity — is visited with probability approaching one as iterations accumulate. Elitism plus this covering argument yields convergence in probability, exactly as in the standard analysis of elitist stochastic search.</p>
</div>
<p>Of course, an asymptotic statement of this kind says nothing about what happens inside a budget of <span class="math inline">\(15{,}000\)</span> evaluations. That question is empirical, and it is the subject of <a href="#sec-benchmarks" class="quarto-xref">Section&nbsp;3</a>.</p>
<p><strong>Exploration–exploitation balance.</strong> Exploration rests mainly on the Knights (<a href="#eq-knight" class="quarto-xref">Equation&nbsp;8</a>) and on the Queens early in the schedule (<a href="#eq-queen" class="quarto-xref">Equation&nbsp;5</a>); exploitation on the Pawns (<a href="#eq-pawn" class="quarto-xref">Equation&nbsp;10</a>), on pinning, and on the en-passant success rule (<a href="#eq-enpassant" class="quarto-xref">Equation&nbsp;12</a>). The balance shifts smoothly through <span class="math inline">\(a(t)\)</span>, <span class="math inline">\(p_{\text{pin}}(t)\)</span>, and <span class="math inline">\(\theta(t)\)</span>, and adapts to the state of the search through the gap-proportional step lengths and the spread-scaled sacrifice budget (<a href="#eq-sacrifice" class="quarto-xref">Equation&nbsp;11</a>).</p>
<p><strong>Parameter economy.</strong> Everything in this paper runs on the one configuration in <a href="#tbl-params" class="quarto-xref">Table&nbsp;2</a>. How sensitive performance is to the role fractions is a fair question we have not yet answered; it is on the future-work list rather than swept under the rug.</p>
</section>
</section>
<section id="sec-benchmarks" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Benchmark Experiments</h1>
<section id="experimental-protocol" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="experimental-protocol"><span class="header-section-number">3.1</span> Experimental protocol</h2>
<p>CA is compared against four established metaheuristics: a real-coded GA with tournament selection, BLX-<span class="math inline">\(\alpha\)</span> crossover, Gaussian mutation, and elitism <span class="citation" data-cites="holland1975adaptation goldberg1989genetic">(<a href="#ref-goldberg1989genetic" role="doc-biblioref">Goldberg, 1989</a>; <a href="#ref-holland1975adaptation" role="doc-biblioref">Holland, 1975</a>)</span>; PSO with linearly decreasing inertia <span class="citation" data-cites="kennedy1995pso">(<a href="#ref-kennedy1995pso" role="doc-biblioref">Kennedy &amp; Eberhart, 1995</a>)</span>; SA <span class="citation" data-cites="kirkpatrick1983sa">(<a href="#ref-kirkpatrick1983sa" role="doc-biblioref">Kirkpatrick et al., 1983</a>)</span>, granted a population-equivalent evaluation budget so the comparison stays fair; and GWO <span class="citation" data-cites="mirjalili2014gwo">(<a href="#ref-mirjalili2014gwo" role="doc-biblioref">Mirjalili et al., 2014</a>)</span>.</p>
<p>The suite consists of six standard functions covering unimodal, ill-conditioned, and highly multimodal terrain (<a href="#tbl-suite" class="quarto-xref">Table&nbsp;3</a>):</p>
<div id="tbl-suite" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-suite-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Benchmark functions (<span class="math inline">\(D = 30\)</span>).
</figcaption>
<div aria-describedby="tbl-suite-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Type</th>
<th>Search domain</th>
<th style="text-align: right;"><span class="math inline">\(f^{*}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1 Sphere</td>
<td>Unimodal</td>
<td><span class="math inline">\([-100, 100]^{30}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>F2 Rosenbrock</td>
<td>Unimodal, ill-conditioned valley</td>
<td><span class="math inline">\([-30, 30]^{30}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>F3 Rastrigin</td>
<td>Multimodal</td>
<td><span class="math inline">\([-5.12, 5.12]^{30}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>F4 Griewank</td>
<td>Multimodal</td>
<td><span class="math inline">\([-600, 600]^{30}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>F5 Ackley</td>
<td>Multimodal</td>
<td><span class="math inline">\([-32, 32]^{30}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>F6 Schwefel 2.22</td>
<td>Unimodal, non-separable norm</td>
<td><span class="math inline">\([-10, 10]^{30}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Every algorithm runs with a population of <span class="math inline">\(N = 30\)</span> for <span class="math inline">\(T = 500\)</span> iterations — a shared core budget of <span class="math inline">\(15{,}000\)</span> population evaluations per run. In the interest of full transparency: CA additionally spends three en-passant probes per iteration and one castling probe every ten iterations (<a href="#sec-ca" class="quarto-xref">Section&nbsp;2</a>), roughly <span class="math inline">\(1{,}550\)</span> extra evaluations, or about ten percent. The gaps reported below span orders of magnitude, so this overhead cannot be what drives them; note also that GWO beats CA <em>despite</em> it. Each algorithm–function pair is repeated over <span class="math inline">\(30\)</span> independent runs, and all algorithms share the same seed at a given run index, so everyone faces the same initial conditions. No parameters were tuned per problem for any method.</p>
<p>Statistics follow <span class="citation" data-cites="derrac2011nonparametric">Derrac et al. (<a href="#ref-derrac2011nonparametric" role="doc-biblioref">2011</a>)</span>: one-way ANOVA to establish that the algorithm factor matters at all, then pairwise two-sided Wilcoxon rank-sum tests (CA against each competitor) at <span class="math inline">\(\alpha = 0.05\)</span>, which make no normality assumption about the final-error distributions.</p>
</section>
<section id="descriptive-results" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="descriptive-results"><span class="header-section-number">3.2</span> Descriptive results</h2>
<p><a href="#tbl-stats" class="quarto-xref">Table&nbsp;4</a> reports the mean, standard deviation, best, and worst final errors for every algorithm–function pair.</p>
<div id="tbl-stats" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[18,12,18,18,17,17]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Mean, standard deviation, best, and worst final objective values over 30 runs (best mean per function in bold).
</figcaption>
<div aria-describedby="tbl-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Algorithm</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std</th>
<th style="text-align: right;">Best</th>
<th style="text-align: right;">Worst</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sphere</td>
<td>CA</td>
<td style="text-align: right;">2.326e-05</td>
<td style="text-align: right;">1.899e-05</td>
<td style="text-align: right;">4.287e-06</td>
<td style="text-align: right;">9.873e-05</td>
</tr>
<tr class="even">
<td>Sphere</td>
<td>GA</td>
<td style="text-align: right;">9.475e-02</td>
<td style="text-align: right;">5.399e-02</td>
<td style="text-align: right;">2.890e-02</td>
<td style="text-align: right;">2.946e-01</td>
</tr>
<tr class="odd">
<td>Sphere</td>
<td>PSO</td>
<td style="text-align: right;">8.455e-01</td>
<td style="text-align: right;">7.216e-01</td>
<td style="text-align: right;">1.194e-01</td>
<td style="text-align: right;">3.131e+00</td>
</tr>
<tr class="even">
<td>Sphere</td>
<td>SA</td>
<td style="text-align: right;">1.013e+04</td>
<td style="text-align: right;">2.218e+03</td>
<td style="text-align: right;">6.628e+03</td>
<td style="text-align: right;">1.612e+04</td>
</tr>
<tr class="odd">
<td>Sphere</td>
<td>GWO</td>
<td style="text-align: right;"><strong>4.678e-31</strong></td>
<td style="text-align: right;">8.194e-31</td>
<td style="text-align: right;">6.431e-33</td>
<td style="text-align: right;">3.925e-30</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td>CA</td>
<td style="text-align: right;">1.001e+02</td>
<td style="text-align: right;">8.363e+01</td>
<td style="text-align: right;">2.080e+01</td>
<td style="text-align: right;">3.801e+02</td>
</tr>
<tr class="odd">
<td>Rosenbrock</td>
<td>GA</td>
<td style="text-align: right;">1.056e+02</td>
<td style="text-align: right;">4.633e+01</td>
<td style="text-align: right;">2.895e+01</td>
<td style="text-align: right;">2.863e+02</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td>PSO</td>
<td style="text-align: right;">6.445e+03</td>
<td style="text-align: right;">2.238e+04</td>
<td style="text-align: right;">8.896e+01</td>
<td style="text-align: right;">9.021e+04</td>
</tr>
<tr class="odd">
<td>Rosenbrock</td>
<td>SA</td>
<td style="text-align: right;">2.185e+07</td>
<td style="text-align: right;">5.693e+06</td>
<td style="text-align: right;">7.615e+06</td>
<td style="text-align: right;">3.486e+07</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td>GWO</td>
<td style="text-align: right;"><strong>2.683e+01</strong></td>
<td style="text-align: right;">6.174e-01</td>
<td style="text-align: right;">2.592e+01</td>
<td style="text-align: right;">2.796e+01</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td>CA</td>
<td style="text-align: right;">2.103e+01</td>
<td style="text-align: right;">6.834e+00</td>
<td style="text-align: right;">9.950e+00</td>
<td style="text-align: right;">3.880e+01</td>
</tr>
<tr class="even">
<td>Rastrigin</td>
<td>GA</td>
<td style="text-align: right;">1.954e+01</td>
<td style="text-align: right;">6.823e+00</td>
<td style="text-align: right;">1.008e+01</td>
<td style="text-align: right;">4.187e+01</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td>PSO</td>
<td style="text-align: right;">5.971e+01</td>
<td style="text-align: right;">1.484e+01</td>
<td style="text-align: right;">3.306e+01</td>
<td style="text-align: right;">9.545e+01</td>
</tr>
<tr class="even">
<td>Rastrigin</td>
<td>SA</td>
<td style="text-align: right;">2.105e+02</td>
<td style="text-align: right;">2.951e+01</td>
<td style="text-align: right;">1.598e+02</td>
<td style="text-align: right;">2.553e+02</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td>GWO</td>
<td style="text-align: right;"><strong>1.023e+01</strong></td>
<td style="text-align: right;">1.078e+01</td>
<td style="text-align: right;">5.684e-14</td>
<td style="text-align: right;">4.680e+01</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td>CA</td>
<td style="text-align: right;">1.064e-02</td>
<td style="text-align: right;">9.397e-03</td>
<td style="text-align: right;">2.798e-05</td>
<td style="text-align: right;">2.744e-02</td>
</tr>
<tr class="odd">
<td>Griewank</td>
<td>GA</td>
<td style="text-align: right;">2.816e-01</td>
<td style="text-align: right;">7.971e-02</td>
<td style="text-align: right;">1.217e-01</td>
<td style="text-align: right;">4.364e-01</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td>PSO</td>
<td style="text-align: right;">6.164e-01</td>
<td style="text-align: right;">2.367e-01</td>
<td style="text-align: right;">2.902e-02</td>
<td style="text-align: right;">1.025e+00</td>
</tr>
<tr class="odd">
<td>Griewank</td>
<td>SA</td>
<td style="text-align: right;">9.190e+01</td>
<td style="text-align: right;">2.324e+01</td>
<td style="text-align: right;">4.826e+01</td>
<td style="text-align: right;">1.563e+02</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td>GWO</td>
<td style="text-align: right;"><strong>4.303e-03</strong></td>
<td style="text-align: right;">9.094e-03</td>
<td style="text-align: right;">0.000e+00</td>
<td style="text-align: right;">3.591e-02</td>
</tr>
<tr class="odd">
<td>Ackley</td>
<td>CA</td>
<td style="text-align: right;">2.413e-01</td>
<td style="text-align: right;">5.617e-01</td>
<td style="text-align: right;">4.383e-04</td>
<td style="text-align: right;">2.013e+00</td>
</tr>
<tr class="even">
<td>Ackley</td>
<td>GA</td>
<td style="text-align: right;">7.757e-02</td>
<td style="text-align: right;">1.486e-02</td>
<td style="text-align: right;">4.767e-02</td>
<td style="text-align: right;">1.099e-01</td>
</tr>
<tr class="odd">
<td>Ackley</td>
<td>PSO</td>
<td style="text-align: right;">1.045e+00</td>
<td style="text-align: right;">5.491e-01</td>
<td style="text-align: right;">8.837e-02</td>
<td style="text-align: right;">2.341e+00</td>
</tr>
<tr class="even">
<td>Ackley</td>
<td>SA</td>
<td style="text-align: right;">4.483e+00</td>
<td style="text-align: right;">3.618e-01</td>
<td style="text-align: right;">3.807e+00</td>
<td style="text-align: right;">5.247e+00</td>
</tr>
<tr class="odd">
<td>Ackley</td>
<td>GWO</td>
<td style="text-align: right;"><strong>3.431e-14</strong></td>
<td style="text-align: right;">4.177e-15</td>
<td style="text-align: right;">2.887e-14</td>
<td style="text-align: right;">3.952e-14</td>
</tr>
<tr class="even">
<td>Schwefel 2.22</td>
<td>CA</td>
<td style="text-align: right;">1.501e-03</td>
<td style="text-align: right;">5.097e-04</td>
<td style="text-align: right;">6.837e-04</td>
<td style="text-align: right;">3.075e-03</td>
</tr>
<tr class="odd">
<td>Schwefel 2.22</td>
<td>GA</td>
<td style="text-align: right;">7.438e-02</td>
<td style="text-align: right;">1.815e-02</td>
<td style="text-align: right;">4.451e-02</td>
<td style="text-align: right;">1.138e-01</td>
</tr>
<tr class="even">
<td>Schwefel 2.22</td>
<td>PSO</td>
<td style="text-align: right;">7.941e-01</td>
<td style="text-align: right;">2.486e+00</td>
<td style="text-align: right;">3.962e-02</td>
<td style="text-align: right;">1.010e+01</td>
</tr>
<tr class="odd">
<td>Schwefel 2.22</td>
<td>SA</td>
<td style="text-align: right;">1.121e+07</td>
<td style="text-align: right;">2.877e+07</td>
<td style="text-align: right;">1.033e+03</td>
<td style="text-align: right;">1.180e+08</td>
</tr>
<tr class="even">
<td>Schwefel 2.22</td>
<td>GWO</td>
<td style="text-align: right;"><strong>9.928e-19</strong></td>
<td style="text-align: right;">9.462e-19</td>
<td style="text-align: right;">1.034e-19</td>
<td style="text-align: right;">4.919e-18</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="convergence-behavior" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="convergence-behavior"><span class="header-section-number">3.3</span> Convergence behavior</h2>
<p><a href="#fig-convergence" class="quarto-xref">Figure&nbsp;2</a> shows the median best-so-far curves, and three patterns are worth pointing out. On F1, F4, and F6, CA keeps descending through the whole run — the en-passant success rule goes on finding improvements deep in the endgame, where GA and PSO stagnated hundreds of iterations earlier. On the ill-conditioned Rosenbrock valley (F2), every population method slows to a crawl, CA and GA tracking each other closely the whole way down. And GWO shows its well-documented strength on this classical suite, converging fastest and deepest on F1, F5, and F6. The distributions of final values behind these curves are shown in <a href="#fig-boxplots" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div id="fig-convergence" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/convergence_all.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Median convergence curves (30 runs, semi-log scale).
</figcaption>
</figure>
</div>
<div id="fig-boxplots" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/boxplots_all.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of final objective values over 30 runs.
</figcaption>
</figure>
</div>
</section>
<section id="statistical-tests" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="statistical-tests"><span class="header-section-number">3.4</span> Statistical tests</h2>
<p>One-way ANOVA confirms that the algorithm factor is highly significant on every function (<a href="#tbl-anova" class="quarto-xref">Table&nbsp;5</a>):</p>
<div id="tbl-anova" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: One-way ANOVA over the five algorithms, per function.
</figcaption>
<div aria-describedby="tbl-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Function</th>
<th style="text-align: right;">F-statistic</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sphere</td>
<td style="text-align: right;">605.073</td>
<td style="text-align: right;">2.388e-89</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td style="text-align: right;">427.005</td>
<td style="text-align: right;">4.067e-79</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td style="text-align: right;">786.005</td>
<td style="text-align: right;">3.621e-97</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td style="text-align: right;">451.249</td>
<td style="text-align: right;">1.011e-80</td>
</tr>
<tr class="odd">
<td>Ackley</td>
<td style="text-align: right;">698.551</td>
<td style="text-align: right;">1.251e-93</td>
</tr>
<tr class="even">
<td>Schwefel 2.22</td>
<td style="text-align: right;">4.403</td>
<td style="text-align: right;">2.175e-03</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The pairwise Wilcoxon tests give the sharper picture (<a href="#tbl-wilcoxon" class="quarto-xref">Table&nbsp;6</a>):</p>
<div id="tbl-wilcoxon" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Wilcoxon rank-sum tests, CA versus each competitor (<span class="math inline">\(\alpha = 0.05\)</span>).
</figcaption>
<div aria-describedby="tbl-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Function</th>
<th>Comparison</th>
<th style="text-align: right;">p-value</th>
<th>Result (α = 0.05)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sphere</td>
<td>CA vs GA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Sphere</td>
<td>CA vs PSO</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>Sphere</td>
<td>CA vs SA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Sphere</td>
<td>CA vs GWO</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA worse</td>
</tr>
<tr class="odd">
<td>Rosenbrock</td>
<td>CA vs GA</td>
<td style="text-align: right;">1.738e-01</td>
<td>not significant</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td>CA vs PSO</td>
<td style="text-align: right;">1.150e-06</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>Rosenbrock</td>
<td>CA vs SA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td>CA vs GWO</td>
<td style="text-align: right;">2.777e-06</td>
<td>CA worse</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td>CA vs GA</td>
<td style="text-align: right;">4.333e-01</td>
<td>not significant</td>
</tr>
<tr class="even">
<td>Rastrigin</td>
<td>CA vs PSO</td>
<td style="text-align: right;">3.510e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td>CA vs SA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Rastrigin</td>
<td>CA vs GWO</td>
<td style="text-align: right;">8.011e-06</td>
<td>CA worse</td>
</tr>
<tr class="odd">
<td>Griewank</td>
<td>CA vs GA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td>CA vs PSO</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>Griewank</td>
<td>CA vs SA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td>CA vs GWO</td>
<td style="text-align: right;">9.193e-06</td>
<td>CA worse</td>
</tr>
<tr class="odd">
<td>Ackley</td>
<td>CA vs GA</td>
<td style="text-align: right;">9.193e-06</td>
<td>CA worse</td>
</tr>
<tr class="even">
<td>Ackley</td>
<td>CA vs PSO</td>
<td style="text-align: right;">2.894e-07</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>Ackley</td>
<td>CA vs SA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Ackley</td>
<td>CA vs GWO</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA worse</td>
</tr>
<tr class="odd">
<td>Schwefel 2.22</td>
<td>CA vs GA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Schwefel 2.22</td>
<td>CA vs PSO</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>Schwefel 2.22</td>
<td>CA vs SA</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>Schwefel 2.22</td>
<td>CA vs GWO</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA worse</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="discussion" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="discussion"><span class="header-section-number">3.5</span> Discussion</h2>
<p>Read together, the tables support a differentiated verdict rather than a slogan. Against PSO and SA, CA is significantly better on all six functions. Against GA it wins four of six — on Sphere, Griewank, and Schwefel 2.22 by several orders of magnitude in mean error — while Rosenbrock and Rastrigin end in statistical ties. Ackley is the one function where GA takes the mean: a few CA runs get stuck on a plateau and drag the average up, even though CA’s <em>median</em> error there (<span class="math inline">\(\sim 10^{-3}\)</span>) is an order of magnitude below GA’s. We flag this rather than hide it, since means and medians disagreeing is itself informative about the tail behavior of the algorithm.</p>
<p>Against GWO the story reverses: GWO is significantly better on all six classical benchmarks, consistent with the aggressive exploitation it is known for on exactly this suite <span class="citation" data-cites="mirjalili2014gwo">(<a href="#ref-mirjalili2014gwo" role="doc-biblioref">Mirjalili et al., 2014</a>)</span>. We see no point in arguing with that result. On standard unconstrained test functions, CA does not overtake GWO, full stop.</p>
<p>What should a practitioner take from this? The rankings are problem-dependent — precisely the situation <span class="citation" data-cites="wolpert1997nfl">Wolpert &amp; Macready (<a href="#ref-wolpert1997nfl" role="doc-biblioref">1997</a>)</span> predicts — so the interesting question is not whether CA wins on Sphere but whether it holds up on structured engineering problems. That is where we go next, and the ranking does change there.</p>
</section>
</section>
<section id="sec-transport" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Transportation Application: Arterial Signal Coordination</h1>
<section id="problem-statement" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="problem-statement"><span class="header-section-number">4.1</span> Problem statement</h2>
<p>Coordinated fixed-time signal timing along an urban arterial is a classic of transportation network optimization, and a spiteful one. The objective surface is multimodal, because different offset combinations produce different locally good “green waves.” The variables are heterogeneous — a common cycle, per-intersection splits, offsets. And the delay model is nonlinear and, in practice, non-differentiable <span class="citation" data-cites="ceylan2004traffic roess2019traffic">(<a href="#ref-ceylan2004traffic" role="doc-biblioref">Ceylan &amp; Bell, 2004</a>; <a href="#ref-roess2019traffic" role="doc-biblioref">Roess et al., 2019</a>)</span>. In short, it is a natural first engineering test for CA.</p>
<p>Our test bed is an eight-intersection arterial with spacings of <span class="math inline">\(450, 380, 520, 300, 610, 420,\)</span> and <span class="math inline">\(350\)</span> m, a progression speed of <span class="math inline">\(50\)</span> km/h, near-saturation two-way traffic (eastbound approach demands between roughly <span class="math inline">\(1{,}240\)</span> and <span class="math inline">\(1{,}400\)</span> veh/h), and conflicting cross-street demands at every junction (<a href="#fig-network" class="quarto-xref">Figure&nbsp;4</a>). Each intersection runs a two-phase plan.</p>
<div id="fig-network" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-network-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/traffic_network.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-network-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Layout of the eight-intersection arterial test bed.
</figcaption>
</figure>
</div>
</section>
<section id="optimization-model" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="optimization-model"><span class="header-section-number">4.2</span> Optimization model</h2>
<p>The decision vector is</p>
<p><span id="eq-decision"><span class="math display">\[
\mathbf{z} = \big(C,\ g_1, \dots, g_8,\ o_2, \dots, o_8\big) \in \mathbb{R}^{16},
\tag{13}\]</span></span></p>
<p>with a common cycle length <span class="math inline">\(C \in [60, 140]\)</span> s, arterial green splits <span class="math inline">\(g_i \in [0.30, 0.75]\)</span>, and offsets <span class="math inline">\(o_i\)</span> expressed as fractions of the cycle (intersection 1 serves as reference). The objective is total network delay in veh·h/h, built from three ingredients.</p>
<p>The first is uniform delay per approach, Webster’s first term <span class="citation" data-cites="webster1958traffic">(<a href="#ref-webster1958traffic" role="doc-biblioref">Webster, 1958</a>)</span>:</p>
<p><span id="eq-webster"><span class="math display">\[
d_1 = \frac{C\,(1 - g)^2}{2\,\big(1 - \min(1, x)\, g\big)},
\tag{14}\]</span></span></p>
<p>where <span class="math inline">\(g\)</span> is the effective green ratio and <span class="math inline">\(x = v/c\)</span> the volume-to-capacity ratio. The second is overflow delay from the HCM time-dependent formulation <span class="citation" data-cites="roess2019traffic">(<a href="#ref-roess2019traffic" role="doc-biblioref">Roess et al., 2019</a>)</span>:</p>
<p><span id="eq-hcm"><span class="math display">\[
d_2 = 900\,T_a \left[ (x - 1) + \sqrt{(x-1)^2 + \frac{8\,k\,I\,x}{c\,T_a}} \right],
\tag{15}\]</span></span></p>
<p>with analysis period <span class="math inline">\(T_a = 0.25\)</span> h, incremental delay factor <span class="math inline">\(k = 0.5\)</span>, and upstream filtering factor <span class="math inline">\(I = 1\)</span>. The third is a progression adjustment: platoons arriving from upstream are shifted by the offset difference minus the travel time, and the mismatch between platoon arrival and the local green window scales the uniform delay up or down, per direction. Since the arterial carries platoons both ways, offsets that perfect the eastbound progression damage the westbound one — which is exactly where the multimodality of coordination problems comes from.</p>
<p>Cross-street phases receive <span class="math inline">\(1 - g_i\)</span> (minus <span class="math inline">\(4\)</span> s lost time per phase) and contribute their own delay, so greedy arterial splits get punished through cross-street oversaturation. All terms are summed over the sixteen arterial approaches and eight cross-street approaches.</p>
</section>
<section id="experimental-setup" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="experimental-setup"><span class="header-section-number">4.3</span> Experimental setup</h2>
<p>CA, GA, PSO, and GWO — the three strongest baselines from <a href="#sec-benchmarks" class="quarto-xref">Section&nbsp;3</a> plus CA — run with <span class="math inline">\(N = 30\)</span>, <span class="math inline">\(T = 300\)</span> iterations (<span class="math inline">\(9{,}000\)</span> core evaluations), and <span class="math inline">\(30\)</span> independent runs each, again without any tuning. SA sat this one out after its uncompetitive benchmark showing.</p>
</section>
<section id="results" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="results"><span class="header-section-number">4.4</span> Results</h2>
<p><a href="#tbl-traffic" class="quarto-xref">Table&nbsp;7</a> summarizes the final delays; <a href="#fig-traffic-conv" class="quarto-xref">Figure&nbsp;5</a> and <a href="#fig-traffic-box" class="quarto-xref">Figure&nbsp;6</a> show the convergence behavior and the spread across runs.</p>
<div id="tbl-traffic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-traffic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Final total delay over 30 runs (best mean in bold).
</figcaption>
<div aria-describedby="tbl-traffic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Mean delay (veh·h/h)</th>
<th style="text-align: right;">Std</th>
<th style="text-align: right;">Best</th>
<th style="text-align: right;">Worst</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA</td>
<td style="text-align: right;">170.618</td>
<td style="text-align: right;">5.236</td>
<td style="text-align: right;">166.526</td>
<td style="text-align: right;">179.540</td>
</tr>
<tr class="even">
<td>GA</td>
<td style="text-align: right;">171.160</td>
<td style="text-align: right;">4.895</td>
<td style="text-align: right;">166.526</td>
<td style="text-align: right;">178.470</td>
</tr>
<tr class="odd">
<td>PSO</td>
<td style="text-align: right;"><strong>169.491</strong></td>
<td style="text-align: right;">3.666</td>
<td style="text-align: right;">166.526</td>
<td style="text-align: right;">179.946</td>
</tr>
<tr class="even">
<td>GWO</td>
<td style="text-align: right;">170.506</td>
<td style="text-align: right;">2.818</td>
<td style="text-align: right;">166.739</td>
<td style="text-align: right;">177.987</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-traffic-wilcoxon" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-traffic-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Wilcoxon rank-sum tests on the signal timing problem.
</figcaption>
<div aria-describedby="tbl-traffic-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th style="text-align: right;">p-value</th>
<th>Result (α = 0.05)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA vs GA</td>
<td style="text-align: right;">3.219e-01</td>
<td>not significant</td>
</tr>
<tr class="even">
<td>CA vs PSO</td>
<td style="text-align: right;">9.293e-01</td>
<td>not significant</td>
</tr>
<tr class="odd">
<td>CA vs GWO</td>
<td style="text-align: right;">7.363e-02</td>
<td>not significant</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-traffic-conv" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-traffic-conv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/traffic_convergence.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-traffic-conv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Median convergence on the arterial signal timing problem.
</figcaption>
</figure>
</div>
<div id="fig-traffic-box" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-traffic-box-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/traffic_boxplot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-traffic-box-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Distribution of final delays over 30 runs.
</figcaption>
</figure>
</div>
<p>Four observations. First, all four algorithms land within about one percent of each other in mean delay (169.5–171.2 veh·h/h), and no pairwise difference involving CA reaches significance (<span class="math inline">\(p &gt; 0.07\)</span> throughout; <a href="#tbl-traffic-wilcoxon" class="quarto-xref">Table&nbsp;8</a>). On this problem class CA is statistically indistinguishable from GA, PSO, and GWO. Second, CA attains the best solution found by any method — <span class="math inline">\(166.526\)</span> veh·h/h, a value GA and PSO also reach — so its operators are clearly capable of locating the same high-quality coordination plan as the strongest baselines. Third, and to us most interesting: the benchmark ranking simply does not carry over. GWO, dominant in <a href="#sec-benchmarks" class="quarto-xref">Section&nbsp;3</a>, holds no advantage here. It is hard to imagine a cleaner illustration of No-Free-Lunch <span class="citation" data-cites="wolpert1997nfl">(<a href="#ref-wolpert1997nfl" role="doc-biblioref">Wolpert &amp; Macready, 1997</a>)</span>, or a better caution against extrapolating benchmark tables into engineering practice. Fourth, we keep the interpretation modest. We do not claim superiority on this problem; the defensible claim is parity with the state of the practice, achieved by a first-generation algorithm running on defaults.</p>
</section>
<section id="the-best-coordination-plan-found" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="the-best-coordination-plan-found"><span class="header-section-number">4.5</span> The best coordination plan found</h2>
<p>The best plan discovered (by CA) selects the minimum cycle, <span class="math inline">\(C = 60\)</span> s — a sensible choice under Webster’s guidance whenever splits can be kept efficient — with the timings of <a href="#tbl-plan" class="quarto-xref">Table&nbsp;9</a>, drawn as a time–space diagram in <a href="#fig-plan" class="quarto-xref">Figure&nbsp;7</a>:</p>
<div id="tbl-plan" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Best signal timing plan found (CA).
</figcaption>
<div aria-describedby="tbl-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cycle length C</td>
<td style="text-align: right;">60.0 s</td>
</tr>
<tr class="even">
<td>Arterial green split g1</td>
<td style="text-align: right;">0.633 (38.0 s)</td>
</tr>
<tr class="odd">
<td>Arterial green split g2</td>
<td style="text-align: right;">0.528 (31.7 s)</td>
</tr>
<tr class="even">
<td>Arterial green split g3</td>
<td style="text-align: right;">0.666 (40.0 s)</td>
</tr>
<tr class="odd">
<td>Arterial green split g4</td>
<td style="text-align: right;">0.498 (29.9 s)</td>
</tr>
<tr class="even">
<td>Arterial green split g5</td>
<td style="text-align: right;">0.624 (37.4 s)</td>
</tr>
<tr class="odd">
<td>Arterial green split g6</td>
<td style="text-align: right;">0.540 (32.4 s)</td>
</tr>
<tr class="even">
<td>Arterial green split g7</td>
<td style="text-align: right;">0.679 (40.7 s)</td>
</tr>
<tr class="odd">
<td>Arterial green split g8</td>
<td style="text-align: right;">0.493 (29.6 s)</td>
</tr>
<tr class="even">
<td>Offset o2</td>
<td style="text-align: right;">32.4 s</td>
</tr>
<tr class="odd">
<td>Offset o3</td>
<td style="text-align: right;">59.8 s</td>
</tr>
<tr class="even">
<td>Offset o4</td>
<td style="text-align: right;">37.2 s</td>
</tr>
<tr class="odd">
<td>Offset o5</td>
<td style="text-align: right;">58.8 s</td>
</tr>
<tr class="even">
<td>Offset o6</td>
<td style="text-align: right;">42.7 s</td>
</tr>
<tr class="odd">
<td>Offset o7</td>
<td style="text-align: right;">13.0 s</td>
</tr>
<tr class="even">
<td>Offset o8</td>
<td style="text-align: right;">38.2 s</td>
</tr>
<tr class="odd">
<td><strong>Total delay</strong></td>
<td style="text-align: right;"><strong>166.526 veh·h/h</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-plan" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/traffic_best_plan.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Time–space representation of the best plan found by CA.
</figcaption>
</figure>
</div>
<p>The offsets form a coherent progression pattern in which consecutive intersections alternate between favoring the eastbound and the westbound platoon — the compromise structure one expects on a heavily loaded two-way arterial.</p>
</section>
<section id="practical-remarks" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="practical-remarks"><span class="header-section-number">4.6</span> Practical remarks</h2>
<p>For a transportation agency the message is straightforward: CA can be used on signal-coordination studies with the same confidence as GA or PSO, and it brings two features practitioners may actually care about. The sacrifice mechanism offers a principled escape from poor offset basins without restarting the search, and the en-passant refinement polishes splits and offsets to fine precision late in the run without a bolt-on local search stage. Extending to cycle-by-cycle stochastic simulation objectives (VISSIM- or SUMO-in-the-loop) is mechanically trivial, since CA needs nothing but function values.</p>
</section>
</section>
<section id="sec-mealpy" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Extended Comparison on Independent Implementations</h1>
<section id="motivation-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="motivation-1"><span class="header-section-number">5.1</span> Motivation</h2>
<p>Every baseline in <a href="#sec-benchmarks" class="quarto-xref">Section&nbsp;3</a> and <a href="#sec-transport" class="quarto-xref">Section&nbsp;4</a> was implemented by us, in the same code style and the same array-vectorized idiom as CA itself. That is standard practice, but it leaves a legitimate question on the table: would CA still look competitive against implementations it had no hand in writing? To answer that, we turn to <code>mealpy</code> <span class="citation" data-cites="vanthieu2023mealpy">(<a href="#ref-vanthieu2023mealpy" role="doc-biblioref">Van Thieu &amp; Mirjalili, 2023</a>)</span>, a large, actively maintained, third-party Python library that currently ships several hundred metaheuristic variants with a common <code>solve(problem, seed=...)</code> interface. We took six well-known algorithms exactly as <code>mealpy</code> ships them — no modification, default hyperparameters — and set them against CA on two transportation problems, one of which has a global optimum we know in closed form.</p>
<p>The six competitors are the Whale Optimization Algorithm (WOA) <span class="citation" data-cites="mirjalili2016whale">(<a href="#ref-mirjalili2016whale" role="doc-biblioref">Mirjalili &amp; Lewis, 2016</a>)</span>, the Sine Cosine Algorithm (SCA) <span class="citation" data-cites="mirjalili2016sca">(<a href="#ref-mirjalili2016sca" role="doc-biblioref">Mirjalili, 2016b</a>)</span>, the Ant Lion Optimizer (ALO) <span class="citation" data-cites="mirjalili2015alo">(<a href="#ref-mirjalili2015alo" role="doc-biblioref">Mirjalili, 2015b</a>)</span>, Moth-Flame Optimization (MFO) <span class="citation" data-cites="mirjalili2015mfo">(<a href="#ref-mirjalili2015mfo" role="doc-biblioref">Mirjalili, 2015a</a>)</span>, Harris Hawks Optimization (HHO) <span class="citation" data-cites="heidari2019hho">(<a href="#ref-heidari2019hho" role="doc-biblioref">Heidari et al., 2019</a>)</span>, and Differential Evolution (DE) <span class="citation" data-cites="storn1997de">(<a href="#ref-storn1997de" role="doc-biblioref">Storn &amp; Price, 1997</a>)</span>. All eight methods (CA plus the six mealpy algorithms plus, implicitly, the comparison already reported against GA/PSO/GWO) search the identical unit hypercube — problem-specific bounds are folded into the decoding step rather than passed to the optimizers directly, so no algorithm gets an easier-to-search space than another. Every algorithm runs with population 30 for 300 iterations across 30 independent runs, with run <span class="math inline">\(r\)</span> of every algorithm seeded identically at <span class="math inline">\(\text{SEED}_0 + r\)</span>.</p>
</section>
<section id="problem-p1-the-arterial-signal-timing-instance" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="problem-p1-the-arterial-signal-timing-instance"><span class="header-section-number">5.2</span> Problem P1: the arterial signal timing instance</h2>
<p>This is the same sixteen-variable coordination problem from <a href="#sec-transport" class="quarto-xref">Section&nbsp;4</a>. <a href="#tbl-mealpy-signal" class="quarto-xref">Table&nbsp;10</a> reports the summary statistics; <a href="#fig-mealpy-convergence" class="quarto-xref">Figure&nbsp;8</a> (left panel) shows median convergence.</p>
<div id="tbl-mealpy-signal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mealpy-signal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: CA versus six mealpy algorithms on the arterial signal timing problem (P1).
</figcaption>
<div aria-describedby="tbl-mealpy-signal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std</th>
<th style="text-align: right;">Best</th>
<th style="text-align: right;">Worst</th>
<th style="text-align: right;">p-value (vs CA)</th>
<th>Result (α = 0.05)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA</td>
<td style="text-align: right;"><strong>170.621</strong></td>
<td style="text-align: right;">5.234</td>
<td style="text-align: right;">166.526</td>
<td style="text-align: right;">179.540</td>
<td style="text-align: right;">—</td>
<td>—</td>
</tr>
<tr class="even">
<td>WOA</td>
<td style="text-align: right;">199.357</td>
<td style="text-align: right;">21.475</td>
<td style="text-align: right;">172.715</td>
<td style="text-align: right;">281.873</td>
<td style="text-align: right;">8.563e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>SCA</td>
<td style="text-align: right;">174.006</td>
<td style="text-align: right;">2.307</td>
<td style="text-align: right;">171.044</td>
<td style="text-align: right;">180.683</td>
<td style="text-align: right;">1.355e-02</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>ALO</td>
<td style="text-align: right;">173.684</td>
<td style="text-align: right;">5.201</td>
<td style="text-align: right;">167.413</td>
<td style="text-align: right;">187.575</td>
<td style="text-align: right;">5.202e-03</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>MFO</td>
<td style="text-align: right;">179.765</td>
<td style="text-align: right;">5.849</td>
<td style="text-align: right;">169.539</td>
<td style="text-align: right;">189.142</td>
<td style="text-align: right;">4.990e-07</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>HHO</td>
<td style="text-align: right;">192.375</td>
<td style="text-align: right;">18.304</td>
<td style="text-align: right;">173.106</td>
<td style="text-align: right;">260.020</td>
<td style="text-align: right;">7.044e-10</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>DE</td>
<td style="text-align: right;">196.222</td>
<td style="text-align: right;">11.382</td>
<td style="text-align: right;">173.619</td>
<td style="text-align: right;">222.264</td>
<td style="text-align: right;">1.395e-10</td>
<td>CA better</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>CA is significantly better than every one of the six competitors here — including SCA and ALO, its closest rivals in this group, at <span class="math inline">\(p = 0.014\)</span> and <span class="math inline">\(p = 0.005\)</span> respectively. WOA, HHO, and DE trail by a wide margin and show markedly higher run-to-run variance (standard deviations of 18–21 veh·h/h, versus 5.2 for CA), which suggests they struggle more than CA does to reliably re-find a good coordination plan across the sixteen-dimensional, periodic offset space. It is worth being honest about what this result does and does not say: GA and PSO, our own implementations from <a href="#sec-transport" class="quarto-xref">Section&nbsp;4</a>, still land in the same ballpark as CA on this problem (<a href="#tbl-traffic" class="quarto-xref">Table&nbsp;7</a>) — the point of this section is not that CA is uniquely strong on signal timing, but that its standing here does not depend on how generously we implemented its rivals.</p>
</section>
<section id="problem-p2-continuous-berth-allocation-with-a-known-optimum" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="problem-p2-continuous-berth-allocation-with-a-known-optimum"><span class="header-section-number">5.3</span> Problem P2: continuous berth allocation with a known optimum</h2>
<p>Independent implementations answer one worry; a problem with a <em>known</em> optimal value answers another, namely whether an algorithm’s apparent superiority is an artifact of comparing everyone’s suboptimality on a problem nobody can actually solve. We borrow Example 1.9 of <span class="citation" data-cites="teodorovic2020quantitative">Teodorović &amp; Janić (<a href="#ref-teodorovic2020quantitative" role="doc-biblioref">2020</a>)</span> (Chapter 1): fifteen ships of known length, arrival time, and required service time must be assigned mooring times and berth positions along a continuous 1,000 m quay within a 1,920-minute horizon, so as to minimize total time spent in port. With unit weights, the mixed-integer formulation in the source has a trivial global optimum: every ship moors the instant it arrives and waits for nothing, giving</p>
<p><span class="math display">\[
F^{*} = \sum_{i=1}^{15} p_i = 4{,}860 \text{ min}.
\]</span></p>
<p>Achieving that bound requires the ship-pair schedule to be simultaneously conflict-free along both the time axis and the quay-position axis — a combinatorial matching problem hiding inside a continuous one, which is precisely what makes the instance a demanding one for a population-based search rather than a token benchmark. We encode each ship’s mooring time <span class="math inline">\(u_i \in [a_i,\ T - p_i]\)</span> and berth position <span class="math inline">\(v_i \in [0,\ S - s_i]\)</span> as decision variables and penalize, rather than hard-constrain, the pairwise rectangle overlap in the time–space diagram, so the search can pass through momentarily infeasible plans on its way to a good one — the same soft-constraint philosophy already used for cross-street oversaturation in <a href="#sec-transport" class="quarto-xref">Section&nbsp;4</a>.</p>
<div id="tbl-mealpy-berth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mealpy-berth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: CA versus six mealpy algorithms on the continuous berth allocation problem (P2), objective in minutes.
</figcaption>
<div aria-describedby="tbl-mealpy-berth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std</th>
<th style="text-align: right;">Best</th>
<th style="text-align: right;">Worst</th>
<th style="text-align: right;">p-value (vs CA)</th>
<th>Result (α = 0.05)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA</td>
<td style="text-align: right;"><strong>8657.0</strong></td>
<td style="text-align: right;">1759.6</td>
<td style="text-align: right;">7056.4</td>
<td style="text-align: right;">16861.9</td>
<td style="text-align: right;">—</td>
<td>—</td>
</tr>
<tr class="even">
<td>WOA</td>
<td style="text-align: right;">45507.4</td>
<td style="text-align: right;">21345.8</td>
<td style="text-align: right;">9388.5</td>
<td style="text-align: right;">93564.7</td>
<td style="text-align: right;">4.286e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>SCA</td>
<td style="text-align: right;">34567.6</td>
<td style="text-align: right;">9683.6</td>
<td style="text-align: right;">19217.2</td>
<td style="text-align: right;">57890.7</td>
<td style="text-align: right;">2.872e-11</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>ALO</td>
<td style="text-align: right;">9912.0</td>
<td style="text-align: right;">3544.1</td>
<td style="text-align: right;">7345.0</td>
<td style="text-align: right;">27033.0</td>
<td style="text-align: right;">3.089e-02</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>MFO</td>
<td style="text-align: right;">21914.8</td>
<td style="text-align: right;">12102.4</td>
<td style="text-align: right;">9112.4</td>
<td style="text-align: right;">52125.0</td>
<td style="text-align: right;">3.012e-10</td>
<td>CA better</td>
</tr>
<tr class="even">
<td>HHO</td>
<td style="text-align: right;">48415.6</td>
<td style="text-align: right;">25410.2</td>
<td style="text-align: right;">12102.0</td>
<td style="text-align: right;">133361.1</td>
<td style="text-align: right;">3.510e-11</td>
<td>CA better</td>
</tr>
<tr class="odd">
<td>DE</td>
<td style="text-align: right;">25765.7</td>
<td style="text-align: right;">12631.0</td>
<td style="text-align: right;">9768.9</td>
<td style="text-align: right;">54967.4</td>
<td style="text-align: right;">1.537e-10</td>
<td>CA better</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>CA’s advantage widens considerably on this problem: its mean objective is roughly a quarter of WOA’s or HHO’s, and it remains significantly better than every competitor, ALO included (<span class="math inline">\(p = 0.031\)</span>), which is otherwise its nearest rival by a comfortable margin over the rest of the field. <a href="#fig-mealpy-convergence" class="quarto-xref">Figure&nbsp;8</a> (right panel) shows why — CA and ALO are the only two methods that make sustained progress past iteration 50, while WOA, SCA, MFO, HHO, and DE largely plateau in the first fifty iterations and then creep for the remaining two hundred and fifty.</p>
<div id="fig-mealpy-convergence" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mealpy-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/mealpy_convergence.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mealpy-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Median convergence on the two transportation problems, CA versus six mealpy algorithms (30 runs). The berth-allocation panel marks the known global optimum.
</figcaption>
</figure>
</div>
<p>We should be candid about how far even the best runs remain from <span class="math inline">\(F^{*} = 4{,}860\)</span>. <a href="#tbl-berth-gap" class="quarto-xref">Table&nbsp;12</a> reports the optimality gap of each algorithm’s best run, together with the residual overlap of its decoded plan.</p>
<div id="tbl-berth-gap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-berth-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Optimality gap and feasibility of the best plan found by each algorithm on P2.
</figcaption>
<div aria-describedby="tbl-berth-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th style="text-align: right;">Best objective (min)</th>
<th style="text-align: right;">Gap to optimum</th>
<th style="text-align: right;">Overlap of best plan (min·m)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA</td>
<td style="text-align: right;">7056.4</td>
<td style="text-align: right;">45.19%</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td>WOA</td>
<td style="text-align: right;">9388.5</td>
<td style="text-align: right;">93.18%</td>
<td style="text-align: right;">878.9</td>
</tr>
<tr class="odd">
<td>SCA</td>
<td style="text-align: right;">19217.2</td>
<td style="text-align: right;">295.42%</td>
<td style="text-align: right;">11752.0</td>
</tr>
<tr class="even">
<td>ALO</td>
<td style="text-align: right;">7345.0</td>
<td style="text-align: right;">51.13%</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td>MFO</td>
<td style="text-align: right;">9112.4</td>
<td style="text-align: right;">87.50%</td>
<td style="text-align: right;">1873.6</td>
</tr>
<tr class="even">
<td>HHO</td>
<td style="text-align: right;">12102.0</td>
<td style="text-align: right;">149.01%</td>
<td style="text-align: right;">1963.4</td>
</tr>
<tr class="odd">
<td>DE</td>
<td style="text-align: right;">9768.9</td>
<td style="text-align: right;">101.01%</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>CA’s best run sits <span class="math inline">\(45\%\)</span> above the true optimum — a substantial gap, and we do not dress it up as anything else. But two things about that gap are worth separating. First, it is the smallest gap on the table by a wide margin: CA’s best solution is roughly <span class="math inline">\(25\)</span>–<span class="math inline">\(35\)</span> percentage points closer to <span class="math inline">\(F^{*}\)</span> than five of its six competitors, and noticeably closer than ALO, its nearest rival. Second, the zero-overlap column shows that CA’s best plan is fully feasible — ships do not actually collide in the time–space diagram — which is not true of WOA, SCA, MFO, or HHO, whose reported objectives still include unresolved penalty mass from residual overlaps. <a href="#fig-berth-plan" class="quarto-xref">Figure&nbsp;9</a> shows CA’s best schedule; every ship occupies its own rectangle with no overlap, though several ships wait appreciably longer than their arrival time, which is exactly where the remaining <span class="math inline">\(45\%\)</span> of the gap comes from.</p>
<div id="fig-berth-plan" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-berth-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/berth_best_plan.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-berth-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Time–space diagram of the best berth allocation plan found by CA. Dotted lines mark each ship’s arrival time; the gap between the arrival line and the left edge of a ship’s rectangle is its waiting time.
</figcaption>
</figure>
</div>
</section>
<section id="what-this-section-does-and-does-not-claim" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="what-this-section-does-and-does-not-claim"><span class="header-section-number">5.4</span> What this section does and does not claim</h2>
<p>We want to be precise about the scope of this comparison. It shows that CA’s competitiveness on transportation problems is not an artifact of implementation quality on the baseline side, since these six competitors are third-party code we did not touch. It does not show that CA is close to solving berth allocation to global optimality — a <span class="math inline">\(45\%\)</span> gap is real and the problem plainly deserves algorithms better tuned to its combinatorial structure than any of the seven general-purpose metaheuristics tested here. What we take from this section is narrower and, we think, still useful: among seven general-purpose population metaheuristics run with default settings and no problem-specific engineering, CA reaches the best and most consistently feasible solutions on both transportation instances tested.</p>
</section>
</section>
<section id="conclusions-and-future-work" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusions and Future Work</h1>
</section>
<section id="conclusions-and-future-work-1" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusions and Future Work</h1>
<section id="summary-of-findings" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="summary-of-findings"><span class="header-section-number">7.1</span> Summary of findings</h2>
<p>This paper introduced the Chess Algorithm, a population-based metaheuristic whose defining feature is a heterogeneous-role architecture: agents dynamically assume the roles of Queens, Rooks, Bishops, Knights, and Pawns around an elite King, each with its own movement geometry, while five strategic mechanisms from chess theory — development, sacrifice, pinning, castling, en passant — plus a threefold-repetition rule govern the search.</p>
<p>Stated with the restraint they deserve, the findings are these. On six classical 30-dimensional benchmarks under matched budgets, CA significantly outperforms GA, PSO, and SA on most of the suite (all six functions against PSO and SA; four of six against GA, with ties on Rosenbrock and Rastrigin). GWO remains significantly stronger than CA on that classical suite, and we regard this as an accurate placement of a first-generation algorithm rather than a defect to argue away. On the eight-intersection arterial problem, CA is statistically indistinguishable from GA, PSO, and GWO and attains the best solution found by any method. And against six third-party implementations from the <code>mealpy</code> library — algorithms none of us wrote a line of — CA is significantly better on both transportation instances tested, including a continuous berth allocation problem with a known optimum, where it also produces the only fully feasible best-found plan among the strongest competitors.</p>
</section>
<section id="limitations" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">7.2</span> Limitations</h2>
<p>The boundaries of the evidence should be stated as plainly as the results. The benchmark suite, though standard, covers six functions at one dimensionality; CEC composition suites and scalability studies at 50–100 dimensions remain to be run. CA consumes roughly ten percent more function evaluations than the baselines through its en-passant and castling probes — disclosed throughout, and far too small to explain order-of-magnitude gaps, but an overhead nonetheless. The transportation studies use analytic delay and penalty models rather than microsimulation. CA’s parameters were fixed a priori and their sensitivity is unquantified. And wall-clock cost per iteration, while of the same order as the baselines, was never the object of optimization.</p>
</section>
<section id="future-work" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="future-work"><span class="header-section-number">7.3</span> Future work</h2>
<p>Several directions strike us as natural. Binary, discrete, and multi-objective variants of CA are the obvious first step — a Pareto “King’s court” of nondominated solutions fits the role architecture almost too neatly. Hybridization is another: replacing the pawn operator with differential-evolution mutation, or switching on the Lévy-flight knight leap (<a href="#eq-levy" class="quarto-xref">Equation&nbsp;9</a>), are one-line experiments in the released code. On the theory side, the en-passant success rule deserves analysis as a <span class="math inline">\((1+\lambda)\)</span>-ES embedded inside a population method. On the applications side, network-wide signal optimization, transit network design, and simulation-based optimization <span class="citation" data-cites="osorio2013simulation">(<a href="#ref-osorio2013simulation" role="doc-biblioref">Osorio &amp; Bierlaire, 2013</a>)</span> are all within reach of the same interface. And a systematic ablation study — knocking out each chess mechanism in turn — is the right way to find out which pieces actually carry the game.</p>
</section>
<section id="closing-remark" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="closing-remark"><span class="header-section-number">7.4</span> Closing remark</h2>
<p>Chess players are taught to judge a move not by the material it wins immediately but by the position it creates. The same standard should apply to a new metaheuristic: CA’s value will be decided not by its row in any single benchmark table but by whether its heterogeneous-role architecture opens useful positions for the optimization problems of transportation engineering. On the evidence assembled here, the opening has been played soundly.</p>
</section>
</section>
<section id="data-and-code-availability" class="level1 unnumbered">
<h1 class="unnumbered">Data and code availability</h1>
<p>All source code, experiment scripts, results, and manuscript sources are openly available at <a href="https://github.com/sabernaseralavi-60/2026_Chess-Algorithm">github.com/sabernaseralavi-60/2026_Chess-Algorithm</a>; the rendered article is served at <a href="https://sabernaseralavi-60.github.io/2026_Chess-Algorithm/">sabernaseralavi-60.github.io/2026_Chess-Algorithm</a>, with the PDF at <a href="paper.pdf"><code>paper.pdf</code></a>. A Persian translation (<code>paper-fa.qmd</code>) is included in the repository and can be rendered locally to Word with Quarto. Every figure and table in this paper is generated by committed scripts:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> src/run_benchmarks.py      <span class="co"># benchmark experiments</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> src/traffic_case_study.py  <span class="co"># arterial signal timing case study</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> src/mealpy_comparison.py   <span class="co"># extended third-party comparison</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render                     <span class="co"># build HTML + PDF + Persian docx</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Random seeds are fixed in the scripts; the results in this paper correspond exactly to the committed outputs in <code>results/</code> and <code>figures/</code>.</p>
</section>
<section id="about-the-corresponding-author" class="level1 unnumbered">
<h1 class="unnumbered">About the corresponding author</h1>
<div class="quarto-layout-panel" data-layout="[22,78]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 22.0%;justify-content: center;">
<p><img src="assets/author_photo.jpg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 78.0%;justify-content: flex-start;">
<p><strong>Seyed Saber Naseralavi</strong> is an Assistant Professor in the Department of Civil Engineering at Shahid Bahonar University of Kerman, Iran. He received his B.Sc. in Civil Engineering from Shahid Bahonar University of Kerman (2004), his M.Sc. in Highway and Transportation Engineering from Iran University of Science and Technology (2006), and his Ph.D.&nbsp;in Highway and Transportation Engineering from Tarbiat Modares University (2011), graduating first in his doctoral cohort at the Faculty of Civil and Environmental Engineering. His research spans traffic safety modeling and surrogate safety measures, traffic flow theory and simulation, travel behavior, machine learning applications in transportation, and metaheuristic optimization for transportation network design. He has authored over 50 refereed journal articles and 80 conference papers, supervised numerous graduate theses, and reviews for several international journals. A provincial chess champion in his youth — first place in the under-12 and under-14 tournaments of Kerman province — he brings to this work a lifelong familiarity with the strategic structure of the game that inspired the algorithm.</p>
</div>
</div>
</div>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-beyer2002es" class="csl-entry" role="listitem">
Beyer, H.-G., &amp; Schwefel, H.-P. (2002). Evolution strategies — a comprehensive introduction. <em>Natural Computing</em>, <em>1</em>(1), 3–52. <a href="https://doi.org/10.1023/A:1015059928466">https://doi.org/10.1023/A:1015059928466</a>
</div>
<div id="ref-ceylan2004traffic" class="csl-entry" role="listitem">
Ceylan, H., &amp; Bell, M. G. H. (2004). Traffic signal timing optimisation based on genetic algorithm approach, including drivers’ routing. <em>Transportation Research Part B: Methodological</em>, <em>38</em>(4), 329–342. <a href="https://doi.org/10.1016/S0191-2615(03)00015-8">https://doi.org/10.1016/S0191-2615(03)00015-8</a>
</div>
<div id="ref-derrac2011nonparametric" class="csl-entry" role="listitem">
Derrac, J., García, S., Molina, D., &amp; Herrera, F. (2011). A practical tutorial on the use of nonparametric statistical tests as a methodology for comparing evolutionary and swarm intelligence algorithms. <em>Swarm and Evolutionary Computation</em>, <em>1</em>(1), 3–18. <a href="https://doi.org/10.1016/j.swevo.2011.02.002">https://doi.org/10.1016/j.swevo.2011.02.002</a>
</div>
<div id="ref-dorigo1996aco" class="csl-entry" role="listitem">
Dorigo, M., Maniezzo, V., &amp; Colorni, A. (1996). Ant system: Optimization by a colony of cooperating agents. <em>IEEE Transactions on Systems, Man, and Cybernetics, Part B</em>, <em>26</em>(1), 29–41. <a href="https://doi.org/10.1109/3477.484436">https://doi.org/10.1109/3477.484436</a>
</div>
<div id="ref-goldberg1989genetic" class="csl-entry" role="listitem">
Goldberg, D. E. (1989). <em>Genetic algorithms in search, optimization, and machine learning</em>. Addison-Wesley.
</div>
<div id="ref-heidari2019hho" class="csl-entry" role="listitem">
Heidari, A. A., Mirjalili, S., Faris, H., Aljarah, I., Mafarja, M., &amp; Chen, H. (2019). Harris hawks optimization: Algorithm and applications. <em>Future Generation Computer Systems</em>, <em>97</em>, 849–872. <a href="https://doi.org/10.1016/j.future.2019.02.028">https://doi.org/10.1016/j.future.2019.02.028</a>
</div>
<div id="ref-holland1975adaptation" class="csl-entry" role="listitem">
Holland, J. H. (1975). <em>Adaptation in natural and artificial systems</em>. University of Michigan Press.
</div>
<div id="ref-karaboga2007abc" class="csl-entry" role="listitem">
Karaboga, D., &amp; Basturk, B. (2007). A powerful and efficient algorithm for numerical function optimization: Artificial bee colony (ABC) algorithm. <em>Journal of Global Optimization</em>, <em>39</em>(3), 459–471. <a href="https://doi.org/10.1007/s10898-007-9149-x">https://doi.org/10.1007/s10898-007-9149-x</a>
</div>
<div id="ref-kennedy1995pso" class="csl-entry" role="listitem">
Kennedy, J., &amp; Eberhart, R. (1995). Particle swarm optimization. <em>Proceedings of ICNN’95 — International Conference on Neural Networks</em>, <em>4</em>, 1942–1948. <a href="https://doi.org/10.1109/ICNN.1995.488968">https://doi.org/10.1109/ICNN.1995.488968</a>
</div>
<div id="ref-kirkpatrick1983sa" class="csl-entry" role="listitem">
Kirkpatrick, S., Gelatt, C. D., &amp; Vecchi, M. P. (1983). Optimization by simulated annealing. <em>Science</em>, <em>220</em>(4598), 671–680. <a href="https://doi.org/10.1126/science.220.4598.671">https://doi.org/10.1126/science.220.4598.671</a>
</div>
<div id="ref-mantegna1994levy" class="csl-entry" role="listitem">
Mantegna, R. N. (1994). Fast, accurate algorithm for numerical simulation of <span>L</span>évy stable stochastic processes. <em>Physical Review E</em>, <em>49</em>(5), 4677–4683. <a href="https://doi.org/10.1103/PhysRevE.49.4677">https://doi.org/10.1103/PhysRevE.49.4677</a>
</div>
<div id="ref-mirjalili2015mfo" class="csl-entry" role="listitem">
Mirjalili, S. (2015a). Moth-flame optimization algorithm: A novel nature-inspired heuristic paradigm. <em>Knowledge-Based Systems</em>, <em>89</em>, 228–249. <a href="https://doi.org/10.1016/j.knosys.2015.07.006">https://doi.org/10.1016/j.knosys.2015.07.006</a>
</div>
<div id="ref-mirjalili2015alo" class="csl-entry" role="listitem">
Mirjalili, S. (2015b). The ant lion optimizer. <em>Advances in Engineering Software</em>, <em>83</em>, 80–98. <a href="https://doi.org/10.1016/j.advengsoft.2015.01.010">https://doi.org/10.1016/j.advengsoft.2015.01.010</a>
</div>
<div id="ref-mirjalili2016dragonfly" class="csl-entry" role="listitem">
Mirjalili, S. (2016a). Dragonfly algorithm: A new meta-heuristic optimization technique for solving single-objective, discrete, and multi-objective problems. <em>Neural Computing and Applications</em>, <em>27</em>(4), 1053–1073. <a href="https://doi.org/10.1007/s00521-015-1920-1">https://doi.org/10.1007/s00521-015-1920-1</a>
</div>
<div id="ref-mirjalili2016sca" class="csl-entry" role="listitem">
Mirjalili, S. (2016b). SCA: A sine cosine algorithm for solving optimization problems. <em>Knowledge-Based Systems</em>, <em>96</em>, 120–133. <a href="https://doi.org/10.1016/j.knosys.2015.12.022">https://doi.org/10.1016/j.knosys.2015.12.022</a>
</div>
<div id="ref-mirjalili2017salp" class="csl-entry" role="listitem">
Mirjalili, S., Gandomi, A. H., Mirjalili, S. Z., Saremi, S., Faris, H., &amp; Mirjalili, S. M. (2017). Salp swarm algorithm: A bio-inspired optimizer for engineering design problems. <em>Advances in Engineering Software</em>, <em>114</em>, 163–191. <a href="https://doi.org/10.1016/j.advengsoft.2017.07.002">https://doi.org/10.1016/j.advengsoft.2017.07.002</a>
</div>
<div id="ref-mirjalili2016whale" class="csl-entry" role="listitem">
Mirjalili, S., &amp; Lewis, A. (2016). The whale optimization algorithm. <em>Advances in Engineering Software</em>, <em>95</em>, 51–67. <a href="https://doi.org/10.1016/j.advengsoft.2016.01.008">https://doi.org/10.1016/j.advengsoft.2016.01.008</a>
</div>
<div id="ref-mirjalili2014gwo" class="csl-entry" role="listitem">
Mirjalili, S., Mirjalili, S. M., &amp; Lewis, A. (2014). Grey wolf optimizer. <em>Advances in Engineering Software</em>, <em>69</em>, 46–61. <a href="https://doi.org/10.1016/j.advengsoft.2013.12.007">https://doi.org/10.1016/j.advengsoft.2013.12.007</a>
</div>
<div id="ref-osorio2013simulation" class="csl-entry" role="listitem">
Osorio, C., &amp; Bierlaire, M. (2013). A simulation-based optimization framework for urban transportation problems. <em>Operations Research</em>, <em>61</em>(6), 1333–1345. <a href="https://doi.org/10.1287/opre.2013.1226">https://doi.org/10.1287/opre.2013.1226</a>
</div>
<div id="ref-roess2019traffic" class="csl-entry" role="listitem">
Roess, R. P., Prassas, E. S., &amp; McShane, W. R. (2019). <em>Traffic engineering</em> (5th ed.). Pearson.
</div>
<div id="ref-storn1997de" class="csl-entry" role="listitem">
Storn, R., &amp; Price, K. (1997). Differential evolution — a simple and efficient heuristic for global optimization over continuous spaces. <em>Journal of Global Optimization</em>, <em>11</em>(4), 341–359. <a href="https://doi.org/10.1023/A:1008202821328">https://doi.org/10.1023/A:1008202821328</a>
</div>
<div id="ref-teodorovic2020quantitative" class="csl-entry" role="listitem">
Teodorović, D., &amp; Janić, M. (2020). <em>Quantitative methods in transportation</em>. CRC Press. <a href="https://doi.org/10.1201/9780429316449">https://doi.org/10.1201/9780429316449</a>
</div>
<div id="ref-vanthieu2023mealpy" class="csl-entry" role="listitem">
Van Thieu, N., &amp; Mirjalili, S. (2023). <span>MEALPY</span>: An open-source library for latest meta-heuristic algorithms in <span>P</span>ython. <em>Journal of Systems Architecture</em>, <em>139</em>, 102871. <a href="https://doi.org/10.1016/j.sysarc.2023.102871">https://doi.org/10.1016/j.sysarc.2023.102871</a>
</div>
<div id="ref-webster1958traffic" class="csl-entry" role="listitem">
Webster, F. V. (1958). <em>Traffic signal settings</em> (Road Research Technical Paper No. 39). Road Research Laboratory.
</div>
<div id="ref-wolpert1997nfl" class="csl-entry" role="listitem">
Wolpert, D. H., &amp; Macready, W. G. (1997). No free lunch theorems for optimization. <em>IEEE Transactions on Evolutionary Computation</em>, <em>1</em>(1), 67–82. <a href="https://doi.org/10.1109/4235.585893">https://doi.org/10.1109/4235.585893</a>
</div>
<div id="ref-yang2009cuckoo" class="csl-entry" role="listitem">
Yang, X.-S., &amp; Deb, S. (2009). Cuckoo search via <span>L</span>évy flights. <em>2009 World Congress on Nature &amp; Biologically Inspired Computing (NaBIC)</em>, 210–214. <a href="https://doi.org/10.1109/NABIC.2009.5393690">https://doi.org/10.1109/NABIC.2009.5393690</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>